SELECT v.taker,
	v.salesrep,
	v.location_id,
	v.customer_id,
	v.customer_name,
	v.order_no,
	v.line_no,
	v.item_id,
	v.item_desc,
	v.qty_open, v.base_unit,
	v.open_value,
	v.customer_po_no,
	v.order_date, v.pick_ticket_print_date, v.required_date,
	v.disposition, v.validation_status, v.approved
FROM asi_view_csr_open_orders AS v
