--DW d_dw_report_studio_canvas
SELECT po_hdr.po_no  ,po_line.line_no  ,inv_mast.item_id  ,po_line.item_description  , po_hdr.company_no  ,po_hdr.order_date  ,po_line.qty_ordered  ,(CASE WHEN po_line.qty_ordered > po_line.qty_received THEN CAST(((po_line.qty_ordered - po_line.qty_received) / po_line.unit_size) * 1.00  AS Decimal(19,9))       ELSE 0.00    END) AS qty_open  ,po_hdr.supplier_id  ,supplier.supplier_name  ,po_line.unit_price  ,inv_loc.qty_on_hand  ,inv_loc.qty_backordered  ,vessel_receipts_line.row_status_flag  ,container_building_po.container_building_uid  ,vessel_receipts_container.container_type_uid  ,inv_loc_stock_status.qty_on_release_schedule  ,container_building_po.po_container_unit_qty  ,container_type.container_type_desc  ,vessel_receipts_hdr.est_avail_ship_date FROM po_line      INNER JOIN po_hdr  ON po_line.po_no = po_hdr.po_no     AND po_line.delete_flag = 'N'     AND po_hdr.delete_flag = 'N'    INNER JOIN vendor  ON vendor.vendor_id = po_hdr.vendor_id            AND vendor.company_id = po_hdr.company_no    INNER JOIN company  ON company.company_id = po_hdr.company_no    INNER JOIN branch  ON branch.company_id = po_hdr.company_no            AND branch.branch_id = po_hdr.branch_id    INNER 
JOIN address  ON address.id = po_hdr.location_id    INNER JOIN supplier  ON supplier.supplier_id = po_hdr.supplier_id    INNER JOIN inv_mast  ON inv_mast.inv_mast_uid = po_line.inv_mast_uid    LEFT JOIN currency_hdr  ON po_hdr.currency_id = 
currency_hdr.currency_id    LEFT JOIN location  ON location.location_id = po_hdr.location_id    LEFT JOIN terms   ON po_hdr.terms =  terms.terms_id    LEFT JOIN class AS po_class1  ON (po_class1.class_id = po_hdr.po_class1) AND (po_class1.class_type = 'PO') 
AND (po_class1.class_number = 1)    LEFT JOIN class AS po_class2  ON (po_class2.class_id = po_hdr.po_class2) AND (po_class2.class_type = 'PO') AND (po_class2.class_number = 2)    LEFT JOIN class AS po_class3  ON (po_class3.class_id = po_hdr.po_class3) AND 
(po_class3.class_type = 'PO') AND (po_class3.class_number = 3)    LEFT JOIN class AS po_class4  ON (po_class4.class_id = po_hdr.po_class4) AND (po_class4.class_type = 'PO') AND (po_class4.class_number = 4)    LEFT JOIN class AS po_class5  ON 
(po_class5.class_id = po_hdr.po_class5) AND (po_class5.class_type = 'PO') AND (po_class5.class_number = 5)    LEFT JOIN inv_loc  ON po_line.inv_mast_uid = inv_loc.inv_mast_uid AND po_hdr.location_id = inv_loc.location_id    LEFT JOIN contacts requested_by  
ON requested_by.id = po_hdr.requested_by    LEFT JOIN product_group  ON inv_loc.product_group_id = product_group.product_group_id      AND product_group.company_id = po_hdr.company_no    LEFT JOIN code_p21 trans_method  ON po_hdr.transmission_method = 
trans_method.code_no    LEFT JOIN code_p21 source_type  ON po_line.source_type = source_type.code_no    LEFT JOIN class as class_id1  ON inv_mast.class_id1 = class_id1.class_id AND class_id1.class_type='IV'  AND class_id1.class_number=1    LEFT JOIN class as 
class_id2  ON inv_mast.class_id2 = class_id2.class_id AND class_id2.class_type='IV'  AND class_id2.class_number=2    LEFT JOIN class as class_id3  ON inv_mast.class_id3 = class_id3.class_id AND class_id3.class_type='IV'  AND class_id3.class_number=3    LEFT JOIN class as class_id4  ON inv_mast.class_id4 = class_id4.class_id AND class_id4.class_type='IV'  AND class_id4.class_number=4    LEFT JOIN class as class_id5  ON inv_mast.class_id5 = class_id5.class_id AND class_id5.class_type='IV'  AND class_id5.class_number=5    INNER JOIN vessel_receipts_line ON (      vessel_receipts_line.po_line_uid = po_line.po_line_uid    )   INNER JOIN container_building_po ON (      container_building_po.po_line_uid = po_line.po_line_uid    )    AND (      container_building_po.container_building_po_uid = vessel_receipts_line.container_building_po_uid    )   INNER JOIN vessel_receipts_container ON (      vessel_receipts_container.vessel_receipts_hdr_uid= vessel_receipts_line.vessel_receipts_hdr_uid    )   JOIN inv_loc_stock_status ON (      inv_loc_stock_status.inv_mast_uid = inv_loc.inv_mast_uid    )    AND (      inv_loc_stock_status.location_id = inv_loc.location_id    )   LEFT JOIN container_type ON (      container_type.container_type_uid = vessel_receipts_container.container_type_uid    )   INNER JOIN vessel_receipts_hdr ON (      vessel_receipts_hdr.vessel_receipts_hdr_uid = vessel_receipts_line.vessel_receipts_hdr_uid    )                        WHERE po_hdr.company_no = '1'   AND po_hdr.order_date >= DATEADD(day, -1000, current_timestamp)   AND po_hdr.location_id = 100   AND (case when po_line.qty_ordered > po_line.qty_received then ((po_line.qty_ordered - po_line.qty_received) / po_line.unit_size) * 1.00         else 0.00    end)  > 0   AND po_line.complete = 'N'   AND vessel_receipts_line.row_status_flag = 702   AND container_building_po.po_container_unit_qty > 0       