--DS d_ds_customer
SELECT customer.customer_id    ,customer.company_id    ,customer.taxable_flag    ,customer.resale_certificate    ,customer.credit_limit    ,customer.credit_limit_used    ,customer.terms_id    ,customer.salesrep_id    ,customer.ar_account_no    
,customer.revenue_account_no    ,customer.cos_account_no    ,customer.allowed_account_no    ,customer.terms_account_no    ,customer.delete_flag    ,customer.date_created    ,customer.date_last_modified    ,customer.last_maintained_by    ,customer.customer_id_string    
,customer.freight_account_no    ,customer.brokerage_account_no    ,customer.class_1id    ,customer.class_2id    ,customer.class_3id    ,customer.class_4id    ,customer.class_5id    ,customer.trade_percent_disc    ,customer.accept_partial_orders    
,customer.acceptable_wait_time    ,customer.price_file_id    ,customer.edi_or_paper    ,customer.security_info    ,customer.interchg_receiver_id    ,customer.intl_san    ,customer.credit_card_no    ,customer.credit_card_type    ,customer.credit_card_name    
,customer.credit_card_expiration_date    ,customer.last_check_number    ,customer.last_check_amount    ,customer.last_check_date    ,customer.receivable_group_id    ,customer.credit_limit_per_order    ,customer.open_item_balance_forward    
,customer.order_acknowledgments    ,customer.accept_interchangeable_items    ,customer.bill_to_contact_id    ,customer.generate_finance_charges    ,customer.limit_max_shipments_per_order    ,customer.credit_limit_check_at_shipment    
,customer.generate_customer_statements    ,customer.sic_code    ,customer.minimum_order_dollar_amount    ,customer.federal_exemption_number    ,customer.other_exemption_number    ,customer.floor_plan_account    ,customer.default_disposition    ,customer.fc_percentage    
,customer.fc_grace_days    ,customer.minimum_finance_charge    ,customer.fc_cycle    ,customer.last_fc_date    ,customer.statement_frequency_id    ,customer.highest_credit_limit_used    ,customer.billed_on_gross_net_qty    ,customer.state_excise_tax_exemption_no    
,customer.credit_status    ,customer.deferred_revenue_account_no    ,customer.override_revenue_by_item    ,customer.pick_ticket_type    ,customer.finance_chg_revenue_account_no    ,customer.finance_charge_ship_to_id    ,customer.customer_name    
,customer.use_consolidated_invoicing    ,customer.ci_for_complete_orders_only    ,customer.ci_print_detail    ,customer.invoice_print_qty    ,customer.fob_required_flag    ,customer.cod_required_flag    ,customer.pricing_method_cd    ,customer.source_price_cd    
,customer.multiplier    ,customer.po_no_required    ,customer.consolidated_ship_to_id    ,customer.lot_bill_summary_on_invoices    ,customer.invoice_batch_uid    ,customer.trading_partner_name    ,customer.generate_statements_by    
,customer.print_zero_dollar_customers    ,customer.pending_payment_account_no    ,customer.print_prices_on_packinglist    ,customer.job_pricing    ,customer.default_rebate_location_id    ,customer.currency_id    ,customer.minimum_order_line_profit    
,customer.maximum_order_line_profit    ,customer.minimum_order_profit    ,customer.maximum_order_profit    ,customer.override_profit_limit    ,customer.include_non_alloc_on_pick_tix    ,customer.exclude_canceld_from_pick_tix    ,customer.date_acct_opened    
,customer.include_non_alloc_on_pack_list    ,customer.exclude_canceld_from_pack_list    ,customer.print_packinglist_in_shipping    ,customer.default_branch_id    ,customer.allow_advance_billing    ,customer.advance_bill_account_no    
,customer.cust_part_no_group_hdr_uid    ,customer.always_use_job_price    ,customer.allow_non_job_item    ,customer.prompt_for_non_job_item    ,customer.allow_exceed_job_qty    ,customer.over_tolerance_percentage    ,customer.under_tolerance_percentage    
,customer.customer_type_cd    ,customer.lead_source_id    ,customer.data_identifier_group_uid    ,customer.passport_customer_id    ,customer.send_ucc128info    ,customer.service_terms_id    ,customer.job_number_required_flag    ,customer.source_type_cd    
,customer.downpayment_percentage    ,customer.req_pymt_upon_release_of_items    ,customer.freight_charge_uid    ,customer.allow_line_item_freight_flag    ,customer.send_dsc856_flag    ,customer.use_last_margin_pricing_flag    ,customer.invoice_comp_cost_cd_tier1    
,customer.promise_date_buffer    ,customer.days_until_quote_expires    ,customer.preferred_flag    ,customer.invoice_comp_cost_cd_tier2    ,customer.invoice_comp_cost_cd_tier3    ,COALESCE(customer.use_vendor_contracts_flag, 'Y') use_vendor_contracts_flag    ,COALESCE(customer.national_account_flag, 'N') national_flag    ,customer.order_priority_uid    ,COALESCE(customer.use_vendor_item_terms_flag, 'N') use_vendor_item_terms_flag    ,customer.foreign_currency_guarantee_type    ,customer.special_labeling_flag    ,customer.special_packaging_flag    ,customer.zoom360_grade    ,customer.zoom360_grade_expiration_date    ,COALESCE(customer.price_label_flag, 'N') price_label_flag    ,customer.days_overdue_for_credit_hold    ,customer.so_po_no_required_flag    ,customer.ucc128_form_filename    ,customer.dealer_wrrty_claims_account_no    ,customer.mfr_no    ,customer.fiscal_year_start_month    ,customer.private_label_flag    ,customer.sales_tax_payable_account_no    ,customer.customer_tax_class    ,customer.servicebench_servicer_no    ,customer.servicebench_alt_servicer_no    ,customer.legacy_id    ,customer.hold_invoice_flag        ,customer.include_dp_summary_on_invoices        ,customer.order_disc_type        ,customer.order_disc_factor      ,customer.drum_deposit_flag      ,customer.cfn_cost_goods_sold_account      ,customer.cfn_receivable_account      ,customer.cfn_revenue_account       ,customer.customer_uid      ,customer.exclude_from_external_tax_calc    ,COALESCE(customer.override_fc_price_conversion_flag, 'N')    ,customer.override_fc_receipt_defaults    ,customer.fc_receipt_default_print    ,customer.fc_receipt_default_email    ,customer.fc_receipt_default_unpriced    ,customer.fc_receipt_default_skinny FROM customer WHERE customer.customer_id = 49889 AND customer.company_id = '1'