select location_id, company_id, date_created, last_maintained_by, gl_account_no, purch_or_transfer, next_due_in_po_cost, sellable, moving_average_cost, standard_cost, inv_min, inv_max, stockable, replenishment_location, months_in_season, product_group_id, purchase_class, date_last_modified, last_rec_po, purchase_discount_group, sales_discount_group, no_charge, replenishment_method, price1, price2, price3, price4, price5, price6, price7, price8, price9, price10, track_bins, default_in_oe, usage_lock, primary_bin, tax_group_id, requisition, inv_mast_uid, lot_bin_integration, default_shipment, buy, make, periods_to_supply_min, periods_to_supply_max, discontinued, allow_ds_discontinued_items, allow_sp_discontinued_items, pattern_manually_edited_flag, demand_pattern_behavior_cd, demand_pattern_cd, behaves_like_lock_flag, delete_flag, price_family_uid, main_bulk_location_flag, drp_item_flag, iva_taxable_flag, iqs_item_flag, slab_track_bins_flag
from dbo.inv_loc
where inv_mast_uid =  32466 and location_id = 100

select location_id, company_id, date_created, last_maintained_by, gl_account_no, purch_or_transfer, next_due_in_po_cost, sellable, moving_average_cost, standard_cost, inv_min, inv_max, stockable, replenishment_location, months_in_season, product_group_id, purchase_class, date_last_modified, last_rec_po, purchase_discount_group, sales_discount_group, no_charge, replenishment_method, price1, price2, price3, price4, price5, price6, price7, price8, price9, price10, track_bins, default_in_oe, usage_lock, primary_bin, tax_group_id, requisition, inv_mast_uid, lot_bin_integration, default_shipment, buy, make, periods_to_supply_min, periods_to_supply_max, discontinued, allow_ds_discontinued_items, allow_sp_discontinued_items, pattern_manually_edited_flag, demand_pattern_behavior_cd, demand_pattern_cd, behaves_like_lock_flag, delete_flag, price_family_uid, main_bulk_location_flag, drp_item_flag, iva_taxable_flag, iqs_item_flag, slab_track_bins_flag
from dbo.inv_loc
where inv_mast_uid =  41210 and location_id = 100

select location_id, company_id, date_created, last_maintained_by, gl_account_no, purch_or_transfer, next_due_in_po_cost, sellable, moving_average_cost, standard_cost, inv_min, inv_max, stockable, replenishment_location, months_in_season, product_group_id, purchase_class, date_last_modified, last_rec_po, purchase_discount_group, sales_discount_group, no_charge, replenishment_method, price1, price2, price3, price4, price5, price6, price7, price8, price9, price10, track_bins, default_in_oe, usage_lock, primary_bin, tax_group_id, requisition, inv_mast_uid, lot_bin_integration, default_shipment, buy, make, periods_to_supply_min, periods_to_supply_max, discontinued, allow_ds_discontinued_items, allow_sp_discontinued_items, pattern_manually_edited_flag, demand_pattern_behavior_cd, demand_pattern_cd, behaves_like_lock_flag, delete_flag, price_family_uid, main_bulk_location_flag, drp_item_flag, iva_taxable_flag, iqs_item_flag, slab_track_bins_flag
from dbo.inv_loc
where inv_mast_uid =  132028 and location_id = 100