--DS d_script_packinglist_hdr
SELECT  p21_fnt_packinglist_hdr.hdrxxxxdef, p21_fnt_packinglist_hdr.title, p21_fnt_packinglist_hdr.header_number, p21_fnt_packinglist_hdr.invoice_date, p21_fnt_packinglist_hdr.customer_id_number, p21_fnt_packinglist_hdr.po_no, p21_fnt_packinglist_hdr.invoice_type, p21_fnt_packinglist_hdr.company_name, p21_fnt_packinglist_hdr.central_phone_number, p21_fnt_packinglist_hdr.total_amount, p21_fnt_packinglist_hdr.format_ship2_addr1, p21_fnt_packinglist_hdr.format_ship2_addr2, p21_fnt_packinglist_hdr.format_ship2_addr3, p21_fnt_packinglist_hdr.format_ship2_addr4, p21_fnt_packinglist_hdr.ship2_address1, p21_fnt_packinglist_hdr.ship2_address2, p21_fnt_packinglist_hdr.ship2_city, p21_fnt_packinglist_hdr.ship2_state, p21_fnt_packinglist_hdr.ship2_postal_code, p21_fnt_packinglist_hdr.ship2_country, p21_fnt_packinglist_hdr.format_bill2_addr1, p21_fnt_packinglist_hdr.format_bill2_addr2, p21_fnt_packinglist_hdr.format_bill2_addr3, p21_fnt_packinglist_hdr.format_bill2_addr4, p21_fnt_packinglist_hdr.format_bill2_addr5, p21_fnt_packinglist_hdr.customer_name, p21_fnt_packinglist_hdr.address1, p21_fnt_packinglist_hdr.address2, p21_fnt_packinglist_hdr.state, p21_fnt_packinglist_hdr.postal_code, p21_fnt_packinglist_hdr.country, p21_fnt_packinglist_hdr.city, p21_fnt_packinglist_hdr.ship2_name, p21_fnt_packinglist_hdr.order_no, p21_fnt_packinglist_hdr.net_due_date, p21_fnt_packinglist_hdr.branch_id, p21_fnt_packinglist_hdr.date_created, 
p21_fnt_packinglist_hdr.date_last_modified, p21_fnt_packinglist_hdr.last_maintained_by, p21_fnt_packinglist_hdr.terms_desc, p21_fnt_packinglist_hdr.branch_description, p21_fnt_packinglist_hdr.format_comp_addr1, 
p21_fnt_packinglist_hdr.format_comp_addr2, p21_fnt_packinglist_hdr.format_comp_addr3, p21_fnt_packinglist_hdr.format_comp_addr4, p21_fnt_packinglist_hdr.mail_address1, p21_fnt_packinglist_hdr.mail_address2, 
p21_fnt_packinglist_hdr.mail_city, p21_fnt_packinglist_hdr.mail_state, p21_fnt_packinglist_hdr.mail_postal_code, p21_fnt_packinglist_hdr.mail_country, p21_fnt_packinglist_hdr.discount_pct, p21_fnt_packinglist_hdr.company_no
, p21_fnt_packinglist_hdr.customer_id_number, p21_fnt_packinglist_hdr.terms_due_date, p21_fnt_packinglist_hdr.delivery_instructions, p21_fnt_packinglist_hdr.order_date, p21_fnt_packinglist_hdr.last_name, 
p21_fnt_packinglist_hdr.first_name, p21_fnt_packinglist_hdr.mi, p21_fnt_packinglist_hdr.primary_salesrep_name, p21_fnt_packinglist_hdr.taker, p21_fnt_packinglist_hdr.route, p21_fnt_packinglist_hdr.validation_status, 
p21_fnt_packinglist_hdr.invoice_class, p21_fnt_packinglist_hdr.amount_paid, p21_fnt_packinglist_hdr.invoice_adjustment_type, p21_fnt_packinglist_hdr.original_document_type, p21_fnt_packinglist_hdr.soldto_customer_id, 
p21_fnt_packinglist_hdr.sold_to_ah_uid, p21_fnt_packinglist_hdr.ship_to_phone, p21_fnt_packinglist_hdr.order_trans_number, p21_fnt_packinglist_hdr.terms_amount, p21_fnt_packinglist_hdr.freight, 
p21_fnt_packinglist_hdr.brokerage, p21_fnt_packinglist_hdr.po_no_append, p21_fnt_packinglist_hdr.pick_ticket_no, p21_fnt_packinglist_hdr.carrier_name, p21_fnt_packinglist_hdr.tracking_no   , p21_fnt_packinglist_hdr.transaction_label  , p21_fnt_packinglist_hdr.date_label  , p21_fnt_packinglist_hdr.bill2_phone  , p21_fnt_packinglist_hdr.order_contact_salutation  , p21_fnt_packinglist_hdr.order_contact_first_name    , p21_fnt_packinglist_hdr.order_contact_mi  , p21_fnt_packinglist_hdr.order_contact_last_name  , p21_fnt_packinglist_hdr.order_contact_name  , p21_fnt_packinglist_hdr.billing_contact_salutation  , p21_fnt_packinglist_hdr.billing_contact_first_name    , p21_fnt_packinglist_hdr.billing_contact_mi  , p21_fnt_packinglist_hdr.billing_contact_last_name  , p21_fnt_packinglist_hdr.billing_contact_name  , p21_fnt_packinglist_hdr.location_id  , p21_fnt_packinglist_hdr.cod_label  , p21_fnt_packinglist_hdr.order_type, p21_fnt_packinglist_hdr.roadnet_route, p21_fnt_packinglist_hdr.roadnet_route_stop, p21_fnt_packinglist_hdr.ship2_address3, p21_fnt_packinglist_hdr.address3, p21_fnt_packinglist_hdr.mail_address3,'N' eco_fee_enabled_flag,'N' trackabout_empty_cylinder_flag  
FROM  p21_fnt_packinglist_hdr ('1', '0', '9999999999', '0', 'ZZZZZZ', 0, 999999999, ' ', 'ZZZZZZZZZZ', ' ', 'ZZZZZ', 0, 999999999, '1990-01-01 00:00:00', '2021-10-26 23:59:59', 2166283, 2166283, 0, 9999 )  