--DS d_script_packinglist_line
SELECT p21_fnt_packing_list_line.linexxxdef,p21_fnt_packing_list_line.qty_ordered,p21_fnt_packing_list_line.qty_shipped,p21_fnt_packing_list_line.qty_remaining,p21_fnt_packing_list_line.remaining_qty,p21_fnt_packing_list_line.header_number,p21_fnt_packing_list_line.qty_requested,p21_fnt_packing_list_line.unit_qty_shipped,p21_fnt_packing_list_line.item_id,p21_fnt_packing_list_line.item_desc,p21_fnt_packing_list_line.unit_price,p21_fnt_packing_list_line.extended_price,p21_fnt_packing_list_line.order_unit_size,p21_fnt_packing_list_line.line_number,p21_fnt_packing_list_line.order_uom,p21_fnt_packing_list_line.extended_desc,p21_fnt_packing_list_line.disposition,p21_fnt_packing_list_line.tax_item,p21_fnt_packing_list_line.other_charge_item,p21_fnt_packing_list_line.other_charge,p21_fnt_packing_list_line.oe_line_line_no,p21_fnt_packing_list_line.qty_invoiced,p21_fnt_packing_list_line.qty_canceled,p21_fnt_packing_list_line.pricing_uom,p21_fnt_packing_list_line.pricing_unit_size,p21_fnt_packing_list_line.ordered_as,p21_fnt_packing_list_line.assembly,p21_fnt_packing_list_line.oe_line_uid,p21_fnt_packing_list_line.company_id,p21_fnt_packing_list_line.order_no,p21_fnt_packing_list_line.customer_id,p21_fnt_packing_list_line.pricing_option,p21_fnt_packing_list_line.oe_line_scheduled,p21_fnt_packing_list_line.net_weight,p21_fnt_packing_list_line.parent_oe_line_uid,
p21_fnt_packing_list_line.invoice_line_type,p21_fnt_packing_list_line.detail_type,COALESCE(p21_fnt_packing_list_line.lot_bill, 'N'),p21_fnt_packing_list_line.invoice_line_item_id,p21_fnt_packing_list_line.currency_desc,
p21_fnt_packing_list_line.cust_po_no, p21_fnt_packing_list_line.contract_bin_id, p21_fnt_packing_list_line.bin_notes,p21_fnt_packing_list_line.line, p21_fnt_packing_list_line.line_feed,p21_fnt_packing_list_line.line_station,
p21_fnt_packing_list_line.contract_part_no,p21_fnt_packing_list_line.order_type,p21_fnt_packing_list_line.inv_mast_uid,oe_line_service.row_status_flag service_order_status,CASE inv_mast.other_charge_item   WHEN 'Y' THEN  
NULL   ELSE  inv_mast.haz_mat_flag    END haz_mat_flag,CASE inv_mast.other_charge_item   WHEN 'Y' THEN  NULL   ELSE  CASE inv_mast.haz_mat_flag WHEN 'Y' 
THEN hazmat_code.hazmat_code_desc ELSE    NULL  END    END hazmat_code_description,inv_mast_msds.msds_flag,inv_mast_msds.revision_date,(SELECT 
MAX(invoice_hdr.invoice_date)   FROM invoice_hdr INNER JOIN invoice_line ON invoice_line.invoice_no = invoice_hdr.invoice_no   WHERE invoice_hdr.company_no = P21_fnt_packing_list_line.company_id   AND invoice_hdr.customer_id_number = 
P21_fnt_packing_list_line.customer_id   AND invoice_line.order_no <> P21_fnt_packing_list_line.order_no   AND invoice_line.inv_mast_uid = P21_fnt_packing_list_line.inv_mast_uid) AS 'item_last_invoice_date',CASE service_bin.bin_id WHEN NULL THEN ''
ELSE 'Bin: 'END bin_label,service_bin.bin_id,service_inv_mast.serial_number,p21_fnt_packing_list_line.ship_to_id    ,p21_fnt_packing_list_line.commodity_code,p21_fnt_packing_list_line.line_seq_no  ,0 sort_line_seq_no  
,p21_fnt_packing_list_line.invoice_line_uid  ,0 total_eco_fee  ,p21_fnt_packing_list_line.upc_code  ,p21_fnt_packing_list_line.ean_code  ,p21_fnt_packing_list_line.gtin_code  ,p21_fnt_packing_list_line.returned_cylinder_quantity  /*MAIN FROM CLAUSE*/  
FROM   p21_fnt_packing_list_line('1','0','9999999999','0','ZZZZZZ',0,999999999,' ','ZZZZZZZZZZ',' ','ZZZZZ',0,999999999,'1990-01-01 00:00:00','2021-10-26 23:59:59',2166283,2166283,0,9999)  LEFT JOIN oe_line_service ON (oe_line_service.oe_line_uid = p21_fnt_packing_list_line.oe_line_uid)  LEFT JOIN oe_line ON (oe_line.oe_line_uid = p21_fnt_packing_list_line.oe_line_uid)  LEFT JOIN inv_mast ON (inv_mast.inv_mast_uid = oe_line.inv_mast_uid)  LEFT OUTER JOIN inv_mast_msds ON (inv_mast_msds.inv_mast_uid = oe_line.inv_mast_uid)  LEFT OUTER JOIN hazmat_code ON (hazmat_code.hazmat_code_uid = inv_mast_msds.hazmat_code_uid)  LEFT JOIN service_inv_mast ON (service_inv_mast.service_inv_mast_uid = oe_line_service.service_inv_mast_uid)  LEFT JOIN bin AS service_bin ON (service_bin.bin_uid = oe_line_service.bin_uid)  /*MAIN WHERE CLAUSE*/  /*MAIN GROUP BY CLAUSE*/  /*MAIN HAVING CLAUSE*/  /*MAIN ORDER BY CLAUSE*/  