SELECT p21_fnt_uc_packinglist_line.linexxxdef    ,p21_fnt_uc_packinglist_line.qty_ordered    ,p21_fnt_uc_packinglist_line.qty_shipped    ,p21_fnt_uc_packinglist_line.qty_remaining    ,p21_fnt_uc_packinglist_line.remaining_qty    ,p21_fnt_uc_packinglist_line.header_number    ,p21_fnt_uc_packinglist_line.qty_requested    ,p21_fnt_uc_packinglist_line.unit_qty_shipped    ,p21_fnt_uc_packinglist_line.item_id    ,p21_fnt_uc_packinglist_line.item_desc    ,p21_fnt_uc_packinglist_line.unit_price    ,p21_fnt_uc_packinglist_line.extended_price    ,p21_fnt_uc_packinglist_line.order_unit_size    ,p21_fnt_uc_packinglist_line.line_number    ,p21_fnt_uc_packinglist_line.order_uom    ,p21_fnt_uc_packinglist_line.extended_desc    ,p21_fnt_uc_packinglist_line.disposition    ,p21_fnt_uc_packinglist_line.tax_item    ,p21_fnt_uc_packinglist_line.other_charge_item    
,p21_fnt_uc_packinglist_line.other_charge    ,p21_fnt_uc_packinglist_line.oe_line_line_no    ,p21_fnt_uc_packinglist_line.qty_invoiced    ,p21_fnt_uc_packinglist_line.qty_canceled    ,p21_fnt_uc_packinglist_line.pricing_uom    
,p21_fnt_uc_packinglist_line.pricing_unit_size    ,p21_fnt_uc_packinglist_line.ordered_as    ,p21_fnt_uc_packinglist_line.assembly    ,p21_fnt_uc_packinglist_line.oe_line_uid    ,p21_fnt_uc_packinglist_line.company_id    
,p21_fnt_uc_packinglist_line.order_no    ,p21_fnt_uc_packinglist_line.customer_id    ,p21_fnt_uc_packinglist_line.pricing_option    ,p21_fnt_uc_packinglist_line.oe_line_scheduled    ,p21_fnt_uc_packinglist_line.net_weight    
,p21_fnt_uc_packinglist_line.parent_oe_line_uid    ,p21_fnt_uc_packinglist_line.invoice_line_type    ,p21_fnt_uc_packinglist_line.detail_type    ,p21_fnt_uc_packinglist_line.lot_bill    ,p21_fnt_uc_packinglist_line.item_id    
,p21_fnt_uc_packinglist_line.user_line_no    ,p21_fnt_uc_packinglist_line.total_pl    ,p21_fnt_uc_packinglist_line.ship_to_id    ,p21_fnt_uc_packinglist_line.currency_desc    ,p21_fnt_uc_packinglist_line.order_type    
,p21_fnt_uc_packinglist_line.sales_tax    ,p21_fnt_uc_packinglist_line.freight_in    ,p21_fnt_uc_packinglist_line.freight_out    ,p21_fnt_uc_packinglist_line.tix_total_tax    ,p21_fnt_uc_packinglist_line.inv_mast_uid    
,p21_fnt_uc_packinglist_line.serial_number    ,p21_fnt_uc_packinglist_line.row_status_flag     ,CASE inv_mast.other_charge_item             WHEN 'Y' THEN                 NULL             ELSE                 
inv_mast.haz_mat_flag         END haz_mat_flag,     CASE inv_mast.other_charge_item             WHEN 'Y' THEN                 NULL             ELSE                 CASE inv_mast.haz_mat_flag                     WHEN 'Y' 
THEN                         hazmat_code.hazmat_code_desc                     ELSE                        NULL                 END         END hazmat_code_description,     inv_mast_msds.msds_flag,     inv_mast_msds.revision_date,     (SELECT MAX(invoice_hdr.invoice_date)        FROM invoice_hdr      INNER JOIN invoice_line ON invoice_line.invoice_no = invoice_hdr.invoice_no        WHERE invoice_hdr.company_no = p21_fnt_uc_packinglist_line.company_id        AND invoice_hdr.customer_id_number = p21_fnt_uc_packinglist_line.customer_id        AND invoice_line.order_no <> p21_fnt_uc_packinglist_line.order_no        AND invoice_line.inv_mast_uid = p21_fnt_uc_packinglist_line.inv_mast_uid) AS 'item_last_invoice_date'    ,inv_mast.commodity_code     ,p21_fnt_uc_packinglist_line.line_seq_no    ,0 sort_line_seq_no    ,0 total_eco_fee    ,p21_fnt_uc_packinglist_line.upc_code    ,p21_fnt_uc_packinglist_line.ean_code    ,p21_fnt_uc_packinglist_line.gtin_code    ,p21_fnt_uc_packinglist_line.cust_po_no    ,p21_fnt_uc_packinglist_line.returned_cylinder_quantity  /*MAIN FROM CLAUSE*/  FROM  p21_fnt_uc_packinglist_line('1',              '0',              '9999999999',              ' ',              'ZZZZZZ',              0,              99999999,              ' ',              'ZZZZZZZZZZ',              ' ',              'ZZZZZZ',              0,              99999999,              '1950-01-01 00:00:00',              '2049-12-31 00:00:00',              2096250,              2096250,              0,              9999,              NULL ,              NULL ,              NULL ,              NULL ,              NULL )  LEFT JOIN oe_line ON (oe_line.oe_line_uid = p21_fnt_uc_packinglist_line.oe_line_uid)  LEFT JOIN inv_mast ON (inv_mast.inv_mast_uid = oe_line.inv_mast_uid)  LEFT OUTER JOIN inv_mast_msds ON (inv_mast_msds.inv_mast_uid = oe_line.inv_mast_uid)  LEFT OUTER JOIN hazmat_code ON (hazmat_code.hazmat_code_uid = inv_mast_msds.hazmat_code_uid)