--DS d_ds_primary_supplier_data_for_tpcx
SELECT drv_PrimarySupplierDataForTPCx.company_id, inventory_supplier.supplier_id, inv_mast.item_id, space(40) c_new_item_id, 'N' c_discard_flag /*MAIN FROM CLAUSE*/ FROM (SELECT inv_loc.company_id, inv_mast.inv_mast_uid, MAX(inventory_supplier_x_loc.inventory_supplier_uid) inventory_supplier_uid FROM inv_mast JOIN inventory_supplier ON inv_mast.inv_mast_uid = inventory_supplier.inv_mast_uid JOIN inventory_supplier_x_loc ON inventory_supplier.inventory_supplier_uid = inventory_supplier_x_loc.inventory_supplier_uid join inv_loc ON inventory_supplier_x_loc.location_id = inv_loc.location_id and inv_mast.inv_mast_uid = inv_loc.inv_mast_uid INNER JOIN company ON company.company_id = inv_loc.company_id WHERE inventory_supplier_x_loc.primary_supplier = 'Y' AND company.tpcx_member = 'Y' GROUP BY inv_loc.company_id, inv_mast.inv_mast_uid ) AS drv_PrimarySupplierDataForTPCx INNER JOIN inv_mast ON drv_PrimarySupplierDataForTPCx.inv_mast_uid = inv_mast.inv_mast_uid INNER JOIN inventory_supplier ON drv_PrimarySupplierDataForTPCx.inventory_supplier_uid = inventory_supplier.inventory_supplier_uid INNER JOIN supplier ON inventory_supplier.supplier_id = supplier.supplier_id /*MAIN WHERE CLAUSE*/ WHERE Coalesce(inv_mast.tpcx_status, 0) > 0 AND Coalesce(supplier.tpcx_rationalized, 'N') = 'Y' AND inv_mast.delete_flag = 'N' AND inv_mast.item_id = '2101035005' /*MAIN GROUP BY CLAUSE*/ /*MAIN HAVING CLAUSE*/ /*MAIN ORDER BY CLAUSE*/ ORDER BY drv_PrimarySupplierDataForTPCx.company_id, inventory_supplier.supplier_id, inv_mast.item_id 

--DS d_ds_assembly_hdr
SELECT inv_mast.item_id , assembly_hdr.labor , assembly_hdr.ship_partial_quantity , assembly_hdr.ship_incomplete_assemblies , assembly_hdr.print_compnts_on_pick_ticket , assembly_hdr.print_components_on_invoice , assembly_hdr.default_disposition , assembly_hdr.overall_assembly_length , assembly_hdr.backflush , assembly_hdr.assembly_days , assembly_hdr.disassembly_days , assembly_hdr.labor_cost_multiplier , assembly_hdr.allow_oe_add_components , assembly_hdr.production_order_processing , assembly_hdr.auto_create_prod_order , inv_mast.item_desc , assembly_hdr.class1 , assembly_hdr.class2 , assembly_hdr.class3 , assembly_hdr.class4 , assembly_hdr.class5 , assembly_hdr.delete_flag , assembly_hdr.date_created , assembly_hdr.date_last_modified , assembly_hdr.last_maintained_by , inv_mast.serialized , inv_mast.track_lots , assembly_hdr.pricing_option , assembly_hdr.print_incomplete_assemblies, assembly_hdr.inv_mast_uid, assembly_hdr.assembly_for_stock, assembly_hdr.assembly_usage_accumulation, assembly_hdr.calc_component_service_level, assembly_hdr.allow_disassembly, assembly_hdr.cost_of_disassembly, assembly_hdr.prorate_cost_by, assembly_hdr.print_return_to_stock_components, assembly_hdr.price_return_to_stock_components, assembly_hdr.hose_assembly_flag, assembly_hdr.hose_overall_length, assembly_hdr.hose_unit_of_measure, assembly_hdr.type, assembly_hdr.process_uid, COALESCE(inv_mast.use_revisions_flag, 'N') use_revisions_flag ,assembly_hdr.print_traveler_with_prodorder ,assembly_hdr.bypass_oe_prod_order_processing ,assembly_hdr.assembly_class_uid ,assembly_hdr.pack_by ,assembly_hdr.minutes_to_make ,dbo.P21_fn_convert_minutes_to_hours_format(assembly_hdr.minutes_to_make) 'time_to_make' FROM assembly_hdr INNER JOIN inv_mast ON (inv_mast.inv_mast_uid = assembly_hdr.inv_mast_uid) WHERE inv_mast.item_id = '2101035005' AND ( (assembly_hdr.delete_flag <> 'Y' ) ) 

--DS d_inventory2
UPDATE inv_mast SET date_last_modified = {ts '2023-06-14 13:22:05.247'}, last_maintained_by = 'mgoldyn', default_selling_unit = 'EA', default_purchasing_unit = 'EA', base_unit = 'EA', redemption_value = 
0.000000000 WHERE item_id = '2101035005' AND item_desc = 'UCFCS210-32' AND delete_flag = 'N' AND weight = 0.000000000000 AND net_weight = 0.000000000000 AND date_created = {ts '2019-06-25 01:31:21.077'} AND 
cube = 0.000000000000 AND inactive = 'N' AND date_inactive IS NULL AND date_reactive IS NULL AND catch_weight_indicator = 'Y' AND purchasing_weight = 0.000000000000 AND upc_or_ean IS NULL AND upc_or_ean_id 
IS NULL AND serialized = 'N' AND product_type = 'R' AND hose = 'N' AND fitting = 'N' AND d_length IS NULL AND short_code = 'UCFCS 210 32           2R08' AND track_lots = 'N' AND class_id1 = 'IPTCI' AND 
class_id2 = 'NOTEPL' AND class_id3 = 'INTERNAL' AND class_id4 IS NULL AND class_id5 = 'SINGLE' AND price1 = 110.000000000 AND price2 = 0.000000000 AND price3 = 0.000000000 AND price4 = 0.000000000 AND 
price5 = 0.000000000 AND price6 = 0.000000000 AND price7 = 102.000000000 AND price8 = 97.000000000 AND price9 = 91.930000000 AND price10 = 88.390000000 AND default_sales_discount_group = 'IPTCI' AND default_purchase_disc_group = 'IPTCI' AND sales_pricing_unit = 'EA' AND sales_pricing_unit_size = 1.0000 AND purchase_pricing_unit = 'EA' AND purchase_pricing_unit_size = 1.0000 AND extended_desc = '4-Bolt Piloted Flange, Set Screw Lock, Bore Dia. 2"S, Wide Inner Race Insert' AND catalog_item = 'N' AND commission_class_id = 'FULL' AND other_charge_item = 'N' AND default_selling_unit = 'EA' AND update_via_pricing_service = 'Y' AND default_purchasing_unit = 'EA' AND ti IS NULL AND hi IS NULL AND convert_quantities = 'N' AND haz_mat_flag = 'N' AND inv_mast_uid = 35007 AND item_terms_discount_pct = 0.00 AND tpcx_status = 0 AND vendor_consigned = 'N' AND use_tags_flag = 'N' AND base_unit = 'EA' AND tag_hold_class_uid IS NULL AND shippable_unit_flag = 'N' AND currency_id IS NULL AND auto_allocation_flag IS NULL AND service_terms_discount_pct = 0.00 AND service_commission_class_id IS NULL AND override_specific_costing = 'N' AND parker_product_cd IS NULL AND parker_division_cd IS NULL AND commodity_code IS NULL AND default_price_family_uid = 2 AND avail_for_sch_delivery_flag = 'N' AND length IS NULL AND width IS NULL AND height IS NULL AND manufacturer_program_type_uid IS NULL AND manufacturer_program_type_pct IS NULL AND item_type_cd = 300 AND cust_parent_inv_mast_uid IS NULL AND source_type_cd IS NULL AND item_sales_tax_class IS NULL AND redemption_value = 0.000000000 AND type_of_sale IS NULL AND pumpoff_item IS NULL AND pumpoff_uom IS NULL AND conoco_division_class_id IS NULL AND buy_get_class IS NULL AND sample_inv_mast_uid IS NULL AND partner_program_labor_item_flag IS NULL AND brand_type IS NULL AND bol_class IS NULL AND rental_item_uid IS NULL AND dflt_dimension_scale IS NULL 

INSERT INTO inv_loc ( location_id, company_id, date_created, last_maintained_by, gl_account_no, purch_or_transfer, next_due_in_po_cost, sellable, moving_average_cost, standard_cost, inv_min, inv_max, stockable, replenishment_location, months_in_season, product_group_id, purchase_class, date_last_modified, last_rec_po, purchase_discount_group, sales_discount_group, no_charge, replenishment_method, price1, price2, price3, price4, price5, price6, price7, price8, price9, price10, track_bins, default_in_oe, usage_lock, primary_bin, tax_group_id, requisition, inv_mast_uid, lot_bin_integration, default_shipment, buy, make, periods_to_supply_min, periods_to_supply_max, discontinued, allow_ds_discontinued_items, allow_sp_discontinued_items, pattern_manually_edited_flag, demand_pattern_behavior_cd, demand_pattern_cd, behaves_like_lock_flag, delete_flag, price_family_uid, main_bulk_location_flag, drp_item_flag, iva_taxable_flag, iqs_item_flag, slab_track_bins_flag ) VALUES ( 100, '1', {ts '2023-06-14 13:22:05.249'}, 'mgoldyn', '14010000100', 'P', 0.000000000, 'Y', 0.000000000, 0.000000000, 0.000000000, 0.000000000, 'N', 100, 0, 'M1', 'N', {ts '2023-06-14 13:22:05.249'}, 0.000000000, 'IPTCI', 'IPTCI', 'N', 'Up To', 110.000000000, 0.000000000, 0.000000000, 0.000000000, 0.000000000, 0.000000000, 102.000000000, 97.000000000, 91.930000000, 88.390000000, 'Y', 'N', 'N', 'NO_PRIMARY', 'NOTAX', 'N', 35007, 'N', 1138, 'Y', 'N', 0, 0, 'N', 'N', 'N', 'N', 1885, 1785, 'N', 'N', 2, 'N', 'N', 'N', 'N', 'N' )

INSERT INTO inv_bin ( company_id, location_id, bin, quantity, date_created, date_last_modified, last_maintained_by, inv_mast_uid, qty_allocated, inv_bin_uid, row_status_flag ) VALUES ( '1', 100, 'NO_PRIMARY', 0.000000000, {ts '2023-06-14 13:22:05.251'}, {ts '2023-06-14 13:22:05.251'}, 'mgoldyn', 35007, 0.000000000, 659662, 1037 )

--DS d_ds_inventory_supplier_x_loc_data_entry
INSERT INTO inventory_supplier_x_loc ( inventory_supplier_x_loc_uid, inventory_supplier_uid, location_id, primary_supplier, average_lead_time, row_status_flag, date_created, date_last_modified, last_maintained_by, vmi_status, loc_list_price, loc_cost ) VALUES ( 687903, 35006, 100, 'Y', 0, 704, {ts '2023-06-14 13:22:05.267'}, {ts '2023-06-14 13:22:05.267'}, 'mgoldyn', 1271, 0.000000000, 0.000000000 )

INSERT INTO inv_loc_msp ( inv_loc_msp_uid, inv_mast_uid, location_id, receipt_process_flag, row_status_flag, date_created, created_by, date_last_modified, last_maintained_by ) VALUES ( 477801, 35007, 100, 'N', 704, {ts '2023-06-14 13:22:05.281'}, 'mgoldyn', {ts '2023-06-14 13:22:05.281'}, 'mgoldyn' )