use P21Sand;

select *
from inv_mast
where item_id = '2308210638'

SELECT  item_uom.unit_of_measure        ,item_uom.unit_size   FROM item_uom    INNER JOIN inv_mast ON ( inv_mast.inv_mast_uid = item_uom.inv_mast_uid )   WHERE ( inv_mast.item_id = '2308210638' ) and             ( item_uom.delete_flag = 'N' )

select inventory_supplier.supplier_id,   inventory_supplier.division_id,   supplier_name,division_name,   CAST (CASE WHEN COALESCE (inventory_supplier_x_loc.loc_list_price,0)<> 0 THEN inventory_supplier_x_loc.loc_list_price    ELSE inventory_supplier.list_price    END AS VARCHAR (255))list_price,   inventory_supplier.supplier_part_no,   inventory_supplier.cost     from inventory_supplier    INNER JOIN supplier ON (inventory_supplier.supplier_id = supplier.supplier_id)   INNER JOIN division ON (inventory_supplier.supplier_id = division.supplier_id)AND    (inventory_supplier.division_id = division.division_id)   INNER JOIN inventory_supplier_x_loc ON (inventory_supplier.inventory_supplier_uid = inventory_supplier_x_loc.inventory_supplier_uid)   WHERE (inventory_supplier.inv_mast_uid = 40491)AND    (inventory_supplier_x_loc.primary_supplier ='Y')AND    (inventory_supplier_x_loc.location_id = 100)   

--DS d_ds_assembly_hdr_oe_4047
SELECT inv_mast.item_id,            assembly_hdr.labor,            assembly_hdr.ship_partial_quantity,            assembly_hdr.ship_incomplete_assemblies,            assembly_hdr.print_compnts_on_pick_ticket,            
assembly_hdr.print_components_on_invoice,            assembly_hdr.default_disposition,            assembly_hdr.overall_assembly_length,            assembly_hdr.backflush,            assembly_hdr.assembly_days,            assembly_hdr.disassembly_days,            
assembly_hdr.labor_cost_multiplier,            assembly_hdr.allow_oe_add_components,            assembly_hdr.production_order_processing,            assembly_hdr.auto_create_prod_order,          assembly_hdr.pricing_option,         assembly_hdr.delete_flag,         inv_mast.item_desc,         inv_mast.serialized,            inv_mast.track_lots,          'N' track_bins,         assembly_hdr.class1,            assembly_hdr.class2,            assembly_hdr.class3,            assembly_hdr.class4,            assembly_hdr.class5,            assembly_hdr.date_created,            assembly_hdr.date_last_modified,            assembly_hdr.last_maintained_by,             assembly_hdr.print_incomplete_assemblies,         assembly_hdr.inv_mast_uid,         assembly_hdr.assembly_for_stock,         assembly_hdr.assembly_usage_accumulation,         assembly_hdr.calc_component_service_level,         assembly_hdr.allow_disassembly,         assembly_hdr.cost_of_disassembly,         assembly_hdr.prorate_cost_by,         assembly_hdr.print_return_to_stock_components,         assembly_hdr.price_return_to_stock_components,         ' ' copy_item_id,         ' ' copy_item_desc,         assembly_hdr.hose_assembly_flag,         assembly_hdr.hose_overall_length,         assembly_hdr.hose_unit_of_measure,     assembly_hdr.minutes_to_make      , ''  revision_level         , COALESCE(inv_mast.use_revisions_flag, 'N') use_revisions_flag         , 0 item_revision_uid         ,assembly_hdr.bypass_oe_prod_order_processing     ,dbo.P21_fn_convert_minutes_to_hours_format(assembly_hdr.minutes_to_make) 'time_to_make' FROM assembly_hdr         INNER JOIN inv_mast ON (inv_mast.inv_mast_uid = assembly_hdr.inv_mast_uid) WHERE inv_mast.item_id = '2101040488' AND ( (assembly_hdr.delete_flag <> 'Y' ) ) 