SELECT TOP 50 ' ' placeholder   ,oe_hdr.order_no  ,oe_hdr.order_date  ,oe_hdr.customer_id  ,address.name  ,users.name  ,p21_view_ds_sales_order_hdr.extended_price  , oe_hdr.company_id  ,oe_hdr.ship2_name  ,oe_hdr.ship2_state  ,oe_hdr.ship2_zip  ,oe_hdr.validation_status  ,p21_view_ds_sales_order_hdr.cc_lines  ,carrier.name  ,oe_hdr.location_id  ,(contacts.first_name +' '+ contacts.mi+' '+contacts.last_name) AS salesrep_name  ,oe_hdr.date_created FROM oe_hdr     INNER JOIN p21_view_ds_sales_order_hdr ON p21_view_ds_sales_order_hdr.oe_hdr_uid = oe_hdr.oe_hdr_uid        AND (oe_hdr.order_type <> 1343 OR oe_hdr.order_type IS NULL)          INNER JOIN address ON address.id = oe_hdr.customer_id    INNER JOIN company ON company.company_id = oe_hdr.company_id     INNER JOIN users ON users.id = oe_hdr.taker    LEFT JOIN oe_hdr_salesrep ON oe_hdr_salesrep.order_number = oe_hdr.order_no        AND oe_hdr_salesrep.primary_salesrep = 'Y'    LEFT JOIN contacts ON contacts.id = oe_hdr_salesrep.salesrep_id    LEFT JOIN quote_hdr ON 
quote_hdr.oe_hdr_uid = oe_hdr.oe_hdr_uid    INNER JOIN  p21_fnt_get_customers('MGOLDYN') AS customer ON customer.customer_id = oe_hdr.customer_id AND customer.company_id = oe_hdr.company_id    INNER JOIN currency_hdr ON customer.currency_id = currency_hdr.currency_id    
LEFT JOIN currency_line ON currency_line.currency_line_uid = oe_hdr.currency_line_uid    INNER JOIN ship_to ON oe_hdr.address_id = ship_to.ship_to_id        AND oe_hdr.company_id = ship_to.company_id     LEFT JOIN shipping_route ON oe_hdr.shipping_route_uid =  
shipping_route.shipping_route_uid    LEFT JOIN [address] AS carrier ON oe_hdr.carrier_id = carrier.id       LEFT JOIN job_price_hdr ON job_price_hdr.job_price_hdr_uid = oe_hdr.job_price_hdr_uid    LEFT JOIN code_p21 AS quote_type ON oe_hdr.quote_type = 
quote_type.code_no    LEFT JOIN code_p21 AS order_type ON oe_hdr.order_type = order_type.code_no    LEFT JOIN code_p21 AS source_code ON oe_hdr.source_code_no = source_code.code_no    LEFT JOIN currency_hdr AS home_currency ON company.home_currency_id = 
home_currency.currency_id    LEFT JOIN oe_hdr_mfr ON (oe_hdr.oe_hdr_uid = oe_hdr_mfr.oe_hdr_uid)      LEFT JOIN location ON oe_hdr.location_id = location.location_id         AND oe_hdr.company_id = location.company_id    LEFT JOIN   class AS ship_to_class1 ON 
ship_to.class1_id = ship_to_class1.class_id AND ship_to_class1.class_type='CS' AND ship_to_class1.class_number=1     LEFT JOIN   class AS ship_to_class2 ON ship_to.class2_id = ship_to_class2.class_id AND ship_to_class2.class_type='CS' AND 
ship_to_class2.class_number=2     LEFT JOIN   class AS ship_to_class3 ON ship_to.class3_id = ship_to_class3.class_id AND ship_to_class3.class_type='CS' AND ship_to_class3.class_number=3     LEFT JOIN   class AS ship_to_class4 ON ship_to.class4_id = 
ship_to_class4.class_id AND ship_to_class4.class_type='CS' AND ship_to_class4.class_number=4     LEFT JOIN   class AS ship_to_class5 ON ship_to.class5_id = ship_to_class5.class_id AND ship_to_class5.class_type='CS' AND ship_to_class5.class_number=5            LEFT JOIN class AS oeclass1  ON oe_hdr.class_1id = oeclass1.class_id AND oeclass1.class_type='OE' AND oeclass1.class_number=1            LEFT JOIN class AS oeclass2  ON oe_hdr.class_2id = oeclass2.class_id AND oeclass2.class_type='OE' AND oeclass2.class_number=2           LEFT JOIN class AS oeclass3  ON oe_hdr.class_3id = oeclass3.class_id AND oeclass3.class_type='OE' AND oeclass3.class_number=3           LEFT JOIN class AS oeclass4  ON oe_hdr.class_4id = oeclass4.class_id AND oeclass4.class_type='OE' AND oeclass4.class_number=4           LEFT JOIN class AS oeclass5  ON oe_hdr.class_5id = oeclass5.class_id AND oeclass5.class_type='OE' AND oeclass5.class_number=5           LEFT JOIN class AS class1  ON customer.class_1id = class1.class_id AND class1.class_type='CS' AND class1.class_number=1           LEFT JOIN class AS class2  ON customer.class_2id = class2.class_id AND class2.class_type='CS' AND class2.class_number=2           LEFT JOIN class AS class3  ON customer.class_3id = class3.class_id AND class3.class_type='CS' AND class3.class_number=3           LEFT JOIN class AS class4  ON customer.class_4id = class4.class_id AND class4.class_type='CS' AND class4.class_number=4           LEFT JOIN class AS class5  ON customer.class_5id = class5.class_id AND class5.class_type='CS' AND class5.class_number=5                
WHERE ( oe_hdr.order_date BETWEEN DATEADD(day, -90, current_timestamp) AND DATEADD(day, -30, current_timestamp) )   AND oe_hdr.company_id = '1' 