INSERT INTO PostalCodes(PostalCode,StaProvName,date_added,date_last_modifiied,last_maintained_by)
VALUES
('DC','District of Columbia',Getdate(),Getdate(),'mgoldyn'), --Not technically a state!
('AL','Alabama',Getdate(),Getdate(),'mgoldyn'),
('AK','Alaska',Getdate(),Getdate(),'mgoldyn'),
('AZ','Arizona',Getdate(),Getdate(),'mgoldyn'),
('AR','Arkansas',Getdate(),Getdate(),'mgoldyn'),
('CA','California',Getdate(),Getdate(),'mgoldyn'),
('CO','Colorado',Getdate(),Getdate(),'mgoldyn'),
('CT','Connecticut',Getdate(),Getdate(),'mgoldyn'),
('DE','Delaware',Getdate(),Getdate(),'mgoldyn'),
('FL','Florida',Getdate(),Getdate(),'mgoldyn'),
('GA','Georgia',Getdate(),Getdate(),'mgoldyn'),
('HI','Hawaii',Getdate(),Getdate(),'mgoldyn'),
('ID','Idaho',Getdate(),Getdate(),'mgoldyn'),
('IL','Illinois',Getdate(),Getdate(),'mgoldyn'),
('IN','Indiana',Getdate(),Getdate(),'mgoldyn'),
('IA','Iowa',Getdate(),Getdate(),'mgoldyn'),
('KS','Kansas',Getdate(),Getdate(),'mgoldyn'),
('KY','Kentucky',Getdate(),Getdate(),'mgoldyn'),
('LA','Louisiana',Getdate(),Getdate(),'mgoldyn'),
('ME','Maine',Getdate(),Getdate(),'mgoldyn'),
('MD','Maryland',Getdate(),Getdate(),'mgoldyn'),
('MA','Massachusetts',Getdate(),Getdate(),'mgoldyn'),
('MI','Michigan',Getdate(),Getdate(),'mgoldyn'),
('MN','Minnesota',Getdate(),Getdate(),'mgoldyn'),
('MS','Mississippi',Getdate(),Getdate(),'mgoldyn'),
('MO','Missouri',Getdate(),Getdate(),'mgoldyn'),
('MT','Montana',Getdate(),Getdate(),'mgoldyn'),
('NE','Nebraska',Getdate(),Getdate(),'mgoldyn'),
('NV','Nevada',Getdate(),Getdate(),'mgoldyn'),
('NH','New Hampshire',Getdate(),Getdate(),'mgoldyn'),
('NJ','New Jersey',Getdate(),Getdate(),'mgoldyn'),
('NM','New Mexico',Getdate(),Getdate(),'mgoldyn'),
('NY','New York',Getdate(),Getdate(),'mgoldyn'),
('NC','North Carolina',Getdate(),Getdate(),'mgoldyn'),
('ND','North Dakota',Getdate(),Getdate(),'mgoldyn'),
('OH','Ohio',Getdate(),Getdate(),'mgoldyn'),
('OK','Oklahoma',Getdate(),Getdate(),'mgoldyn'),
('OR','Oregon',Getdate(),Getdate(),'mgoldyn'),
('PA','Pennsylvania',Getdate(),Getdate(),'mgoldyn'),
('RI','Rhode Island',Getdate(),Getdate(),'mgoldyn'),
('SC','South Carolina',Getdate(),Getdate(),'mgoldyn'),
('SD','South Dakota',Getdate(),Getdate(),'mgoldyn'),
('TN','Tennessee',Getdate(),Getdate(),'mgoldyn'),
('TX','Texas',Getdate(),Getdate(),'mgoldyn'),
('UT','Utah',Getdate(),Getdate(),'mgoldyn'),
('VT','Vermont',Getdate(),Getdate(),'mgoldyn'),
('VA','Virginia',Getdate(),Getdate(),'mgoldyn'),
('WA','Washington',Getdate(),Getdate(),'mgoldyn'),
('WV','West Virginia',Getdate(),Getdate(),'mgoldyn'),
('WI','Wisconsin',Getdate(),Getdate(),'mgoldyn'),
('WY','Wyoming',Getdate(),Getdate(),'mgoldyn');