use P21;

SELECT  invoice_hdr.company_no  ,invoice_hdr.invoice_no  ,invoice_line.line_no  ,invoice_line.item_id  ,invoice_line.item_desc  ,customer.customer_id  ,customer.customer_name  ,invoice_hdr.ship2_name  ,invoice_hdr.ship_to_id  ,inv_mast.item_id  
,inv_mast.item_desc  ,invoice_line.qty_shipped  ,oe_line.required_date  ,invoice_hdr.invoice_date  ,invoice_hdr.order_no  ,oe_hdr.po_no  ,oe_hdr.order_date  ,oe_hdr.location_id  ,inv_mast.class_id1  ,customer.class_1id  ,class_id1.class_description  ,oe_pick_ticket.print_date  ,oe_pick_ticket.location_id  ,oe_line.source_loc_id 
FROM invoice_line
INNER JOIN invoice_hdr  
ON invoice_hdr.invoice_no = invoice_line.invoice_no     
INNER JOIN  p21_fnt_get_customers('MGOLDYN') AS customer 
ON customer.customer_id = invoice_hdr.customer_id_number AND customer.company_id = invoice_hdr.company_no    
LEFT JOIN inv_mast   ON (inv_mast.inv_mast_uid = invoice_line.inv_mast_uid)    LEFT JOIN product_group  ON invoice_line.product_group_id = product_group.product_group_id          AND invoice_hdr.company_no = product_group.company_id    LEFT JOIN supplier   ON invoice_line.supplier_id = supplier.supplier_id    LEFT JOIN price_family   ON (price_family.price_family_uid = inv_mast.default_price_family_uid)    LEFT JOIN discount_group AS sales_discount_group   ON (sales_discount_group.discount_group_id = invoice_line.sales_discount_group_id)    LEFT JOIN discount_group AS purchase_disc_group   ON (purchase_disc_group.discount_group_id = inv_mast.default_purchase_disc_group)    LEFT JOIN inventory_supplier   ON inv_mast.inv_mast_uid = inventory_supplier.inv_mast_uid      AND inventory_supplier.supplier_id = invoice_line.supplier_id    LEFT JOIN class as class_id1  ON inv_mast.class_id1 = class_id1.class_id AND class_id1.class_type='IV' AND class_id1.class_number=1    LEFT JOIN class as class_id2  ON inv_mast.class_id2 = class_id2.class_id AND class_id2.class_type='IV' AND class_id2.class_number=2    LEFT JOIN class as class_id3  ON inv_mast.class_id3 = class_id3.class_id AND class_id3.class_type='IV' AND class_id3.class_number=3    LEFT JOIN class as class_id4  ON inv_mast.class_id4 = class_id4.class_id AND class_id4.class_type='IV' AND class_id4.class_number=4    LEFT JOIN class as class_id5  ON inv_mast.class_id5 = class_id5.class_id AND class_id5.class_type='IV' AND class_id5.class_number=5    LEFT JOIN manufacturing_class  ON inventory_supplier.manufacturing_class_id = manufacturing_class.manufacturing_class_id    LEFT JOIN oe_hdr  ON invoice_line.order_no = oe_hdr.order_no    LEFT JOIN oe_line ON invoice_line.order_no = 
oe_line.order_no AND invoice_line.oe_line_number = oe_line.line_no    LEFT JOIN location AS source_location  ON source_location.location_id = oe_line.source_loc_id    LEFT JOIN location ON location.location_id = oe_hdr.location_id    LEFT JOIN inv_loc ON 
invoice_hdr.sales_location_id = inv_loc.location_id AND inv_loc.inv_mast_uid = invoice_line.inv_mast_uid    INNER JOIN company ON invoice_hdr.company_no = company.company_id       LEFT JOIN currency_line ON currency_line.currency_line_uid = 
invoice_hdr.currency_line_uid    LEFT JOIN currency_hdr ON currency_hdr.currency_id = (COALESCE(currency_line.to_currency_id, company.home_currency_id))    LEFT JOIN code_p21 AS code_invoice_line_type  ON invoice_line.invoice_line_type = 
code_invoice_line_type.code_no    LEFT JOIN class AS class1  ON customer.class_1id = class1.class_id AND class1.class_type='CS' AND class1.class_number=1     LEFT JOIN class AS class2  ON customer.class_2id = class2.class_id AND class2.class_type='CS' AND 
class2.class_number=2     LEFT JOIN class AS class3  ON customer.class_3id = class3.class_id AND class3.class_type='CS' AND class3.class_number=3     LEFT JOIN class AS class4  ON customer.class_4id = class4.class_id AND class4.class_type='CS' AND 
class4.class_number=4     LEFT JOIN class AS class5  ON customer.class_5id = class5.class_id AND class5.class_type='CS' AND class5.class_number=5     LEFT JOIN ship_to  ON  invoice_hdr.ship_to_id = ship_to.ship_to_id AND  invoice_hdr.company_no = ship_to.company_id      
LEFT JOIN   class AS ship_to_class1 ON ship_to.class1_id = ship_to_class1.class_id AND ship_to_class1.class_type='CS' AND ship_to_class1.class_number=1     LEFT JOIN   class AS ship_to_class2 ON ship_to.class2_id = ship_to_class2.class_id AND 
ship_to_class2.class_type='CS' AND ship_to_class2.class_number=2     LEFT JOIN   class AS ship_to_class3 ON ship_to.class3_id = ship_to_class3.class_id AND ship_to_class3.class_type='CS' AND ship_to_class3.class_number=3     LEFT JOIN   class AS ship_to_class4 ON ship_to.class4_id = ship_to_class4.class_id AND ship_to_class4.class_type='CS' AND ship_to_class4.class_number=4     LEFT JOIN   class AS ship_to_class5 ON ship_to.class5_id = ship_to_class5.class_id AND ship_to_class5.class_type='CS' AND ship_to_class5.class_number=5     LEFT JOIN class AS oeclass1  ON oe_hdr.class_1id = oeclass1.class_id AND oeclass1.class_type='OE' AND oeclass1.class_number=1      LEFT JOIN class AS oeclass2  ON oe_hdr.class_2id = oeclass2.class_id AND oeclass2.class_type='OE' AND oeclass2.class_number=2     LEFT JOIN class AS oeclass3  ON oe_hdr.class_3id = oeclass3.class_id AND oeclass3.class_type='OE' AND oeclass3.class_number=3     LEFT JOIN class AS oeclass4  ON oe_hdr.class_4id = oeclass4.class_id AND oeclass4.class_type='OE' AND oeclass4.class_number=4     LEFT JOIN class AS oeclass5  ON oe_hdr.class_5id = oeclass5.class_id AND oeclass5.class_type='OE' AND oeclass5.class_number=5     LEFT JOIN purchase_class   ON inv_loc.purchase_class = purchase_class.purchase_class_id    LEFT JOIN shipping_route ON oe_hdr.shipping_route_uid =  shipping_route.shipping_route_uid    LEFT JOIN invoice_hdr_salesrep ON ( invoice_hdr_salesrep.invoice_number = invoice_hdr.invoice_no      AND invoice_hdr_salesrep.salesrep_id = invoice_hdr.salesrep_id AND invoice_hdr_salesrep.primary_salesrep='Y' )    LEFT JOIN contacts ON contacts.id = invoice_hdr_salesrep.salesrep_id    LEFT JOIN contacts as oe_contact on oe_contact.id = oe_hdr.contact_id    JOIN oe_pick_ticket ON   (oe_pick_ticket.invoice_no = invoice_hdr.invoice_no)                      WHERE invoice_hdr.company_no = '1'   AND customer.customer_name LIKE 'Grainger%'   AND invoice_hdr.invoice_date >= DATEADD(day, -90, current_timestamp)