SELECT oe_hdr.order_no  ,oe_line.line_no  ,oe_hdr.order_date  ,inv_mast.item_id  ,inv_mast.item_desc  , oe_hdr.company_id  ,oe_hdr.po_no  ,oe_hdr.customer_id  ,customer.customer_name ,oe_hdr.address_id  ,oe_hdr.ship2_name  
,oe_line.qty_ordered  ,oe_line.qty_allocated  ,oe_line.qty_invoiced  ,oe_line.required_date  ,(COALESCE(oe_line.disposition,'')) AS disposition  ,oe_line.scheduled  ,oe_line.qty_on_pick_tickets  ,oe_hdr.packing_basis  ,oe_line.source_loc_id 
FROM oe_line     INNER JOIN 
inv_mast ON inv_mast.inv_mast_uid = oe_line.inv_mast_uid        AND inv_mast.product_type <> 'B' AND oe_line.service_labor_uid is null       AND ( oe_line.delete_flag = 'N' )     INNER JOIN oe_hdr ON oe_line.order_no = oe_hdr.order_no       AND ( oe_hdr.delete_flag = 
'N' )    LEFT JOIN quote_hdr on quote_hdr.oe_hdr_uid = oe_hdr.oe_hdr_uid    LEFT JOIN p21_view_ds_service_labor_by_oeline AS service_labor ON service_labor.oe_line_uid = oe_line.oe_line_uid    INNER JOIN company ON company.company_id = oe_hdr.company_id      INNER JOIN 
oe_hdr_salesrep ON oe_hdr_salesrep.order_number = oe_hdr.order_no        AND ( oe_hdr_salesrep.primary_salesrep = 'Y' )    INNER JOIN contacts ON contacts.id = oe_hdr_salesrep.salesrep_id     INNER JOIN p21_fnt_get_customers('MGOLDYN') AS customer ON customer.customer_id = oe_hdr.customer_id        AND customer.company_id = oe_hdr.company_id    INNER JOIN users ON users.id = oe_hdr.taker    INNER JOIN location ON location.location_id = oe_hdr.location_id    INNER JOIN currency_hdr ON customer.currency_id = currency_hdr.currency_id     LEFT JOIN oe_line_promise_date ON (oe_line_promise_date.oe_line_uid = oe_line.oe_line_uid)    INNER JOIN ship_to on oe_hdr.address_id = ship_to.ship_to_id        AND oe_hdr.company_id = ship_to.company_id    INNER JOIN address ON address.id = customer.customer_id    INNER JOIN oe_line AS oe_line_parent ON oe_line.oe_line_uid = oe_line_parent.oe_line_uid AND oe_line_parent.parent_oe_line_uid = 0    LEFT JOIN oe_line_lot_billing on oe_line_lot_billing.oe_line_uid = oe_line.oe_line_uid     LEFT JOIN currency_line ON (currency_line.currency_line_uid = oe_hdr.currency_line_uid)    LEFT JOIN code_p21 AS order_type ON order_type.code_no = oe_hdr.order_type    LEFT JOIN code_p21 AS source_code ON oe_hdr.source_code_no = source_code.code_no    LEFT JOIN job_price_hdr ON job_price_hdr.job_price_hdr_uid = oe_hdr.job_price_hdr_uid    LEFT JOIN code_p21 AS quote_type ON oe_hdr.quote_type = quote_type.code_no    LEFT JOIN address AS carrier ON oe_hdr.carrier_id = carrier.id       LEFT JOIN shipping_route ON oe_hdr.shipping_route_uid =  shipping_route.shipping_route_uid    LEFT JOIN discount_group AS sales_discount_group   ON (sales_discount_group.discount_group_id = inv_mast.default_sales_discount_group)    LEFT JOIN discount_group AS purchase_disc_group   ON (purchase_disc_group.discount_group_id = inv_mast.default_purchase_disc_group)    LEFT JOIN price_family   ON (price_family.price_family_uid = inv_mast.default_price_family_uid)    LEFT JOIN inventory_supplier   ON inv_mast.inv_mast_uid = inventory_supplier.inv_mast_uid       AND inventory_supplier.supplier_id 
= oe_line.supplier_id    LEFT JOIN supplier ON supplier.supplier_id = oe_line.supplier_id    LEFT JOIN manufacturing_class  ON inventory_supplier.manufacturing_class_id = manufacturing_class.manufacturing_class_id    LEFT JOIN class as class_id1  ON inv_mast.class_id1 = 
class_id1.class_id AND class_id1.class_type='IV' AND class_id1.class_number=1    LEFT JOIN class as class_id2  ON inv_mast.class_id2 = class_id2.class_id AND class_id2.class_type='IV' AND class_id2.class_number=2    LEFT JOIN class as class_id3  ON inv_mast.class_id3 = 
class_id3.class_id AND class_id3.class_type='IV' AND class_id3.class_number=3    LEFT JOIN class as class_id4  ON inv_mast.class_id4 = class_id4.class_id AND class_id4.class_type='IV' AND class_id4.class_number=4    LEFT JOIN class as class_id5  ON inv_mast.class_id5 = 
class_id5.class_id AND class_id5.class_type='IV' AND class_id5.class_number=5    LEFT JOIN location AS source_location  ON source_location.location_id = oe_line.source_loc_id    LEFT JOIN location AS location_ship ON location_ship.location_id = oe_line.ship_loc_id    
LEFT JOIN inv_loc   ON oe_line.source_loc_id = inv_loc.location_id AND inv_loc.inv_mast_uid = oe_line.inv_mast_uid    LEFT JOIN purchase_class   ON inv_loc.purchase_class = purchase_class.purchase_class_id    LEFT JOIN class AS class1  ON customer.class_1id = 
class1.class_id AND class1.class_type='CS' AND class1.class_number=1     LEFT JOIN class AS class2  ON customer.class_2id = class2.class_id AND class2.class_type='CS' AND class2.class_number=2     LEFT JOIN class AS class3  ON customer.class_3id = class3.class_id AND 
class3.class_type='CS' AND class3.class_number=3     LEFT JOIN class AS class4  ON customer.class_4id = class4.class_id AND class4.class_type='CS' AND class4.class_number=4     LEFT JOIN class AS class5  ON customer.class_5id = class5.class_id AND class5.class_type='CS' 
AND class5.class_number=5      LEFT JOIN contacts AS invhdr_salesrep  ON oe_hdr_salesrep.salesrep_id = invhdr_salesrep.id     LEFT JOIN currency_hdr AS home_currency  ON company.home_currency_id = home_currency.currency_id    LEFT JOIN contacts as oe_contact on oe_contact.id = oe_hdr.contact_id    LEFT JOIN    class AS oeclass1  ON oe_hdr.class_1id = oeclass1.class_id AND oeclass1.class_type='OE' AND oeclass1.class_number=1      LEFT JOIN    class AS oeclass2  ON oe_hdr.class_2id = oeclass2.class_id AND oeclass2.class_type='OE' AND oeclass2.class_number=2     LEFT JOIN    class AS oeclass3  ON oe_hdr.class_3id = oeclass3.class_id AND oeclass3.class_type='OE' AND oeclass3.class_number=3    LEFT JOIN    class AS oeclass4  ON oe_hdr.class_4id = oeclass4.class_id AND oeclass4.class_type='OE' AND oeclass4.class_number=4     LEFT JOIN    class AS oeclass5  ON oe_hdr.class_5id = oeclass5.class_id AND oeclass5.class_type='OE' AND oeclass5.class_number=5     LEFT JOIN   class AS ship_to_class1 ON ship_to.class1_id = ship_to_class1.class_id AND ship_to_class1.class_type='CS' AND ship_to_class1.class_number=1    LEFT JOIN   class AS ship_to_class2 ON ship_to.class2_id = ship_to_class2.class_id AND ship_to_class2.class_type='CS' AND ship_to_class2.class_number=2     LEFT JOIN   class AS ship_to_class3 ON ship_to.class3_id = ship_to_class3.class_id AND ship_to_class3.class_type='CS' AND ship_to_class3.class_number=3    LEFT JOIN   class AS ship_to_class4 ON ship_to.class4_id = ship_to_class4.class_id AND ship_to_class4.class_type='CS' AND ship_to_class4.class_number=4    LEFT JOIN   class AS ship_to_class5 ON ship_to.class5_id = ship_to_class5.class_id AND ship_to_class5.class_type='CS' AND ship_to_class5.class_number=5               
WHERE oe_hdr.company_id = '1'   AND customer.customer_name LIKE 'Grainger%'   AND oe_line.complete = 'N'   AND oe_hdr.projected_order = 'N'