/*
	07/14/2020 Per george he wants all quotes from eservice@ptintl.com
	Number 8 is test quote
	24 PTI House
*/
--use P21Play;

select alert_implementation_uid,subject,header,line_item,footer,sender_name,sender_email_address
from alert_message
where alert_implementation_uid between 12 and 27

update alert_message
set sender_name = '',sender_email_address = '' where alert_implementation_uid between 12 and 27

select alert_implementation_uid,subject,header,line_item,footer,sender_name,sender_email_address
from alert_message
where alert_implementation_uid between 12 and 27

/*
update alert_message
set footer = 'Email generated by New Quote, Have a great day!',sender_name = 'Inside Sales',sender_email_address = '<taker_email>' where alert_implementation_uid = 24

update alert_message
set footer = 'Correo electrónico generado por New Quote, ¡que tengas un gran día!',sender_name = 'Ventas interiores',sender_email_address = '<taker_email>'   where alert_implementation_uid = 24

select subject,header,line_item,footer,sender_name,sender_email_address
from alert_message
where alert_implementation_uid = 24
*/