SELECT        dbo.vwinventory_lvl1.container, dbo.vwinventory_lvl1.total_qty_on_container, dbo.vwinventory_lvl1.future_cost, dbo.vwinventory_lvl1.effective_date, dbo.vwinventory_lvl1.old_bin, 
                         ROUND(dbo.vwinventory_lvl1.forecast_usage * ISNULL(periods_to_supply.periods_to_supply, 1.3), 0) AS forecast_1_3, 
                         dbo.InlineMax(ROUND(dbo.vwinventory_lvl1.forecast_usage * ISNULL(periods_to_supply.periods_to_supply, 1.3), 0), dbo.vwinventory_lvl1.order_point) AS forecast_point, CASE WHEN replenishment_method IN ('OP/OQ', 
                         'min/max') THEN Maximum ELSE WQMetaData.dbo.inlinemax(round(forecast_usage * isnull(periods_to_supply, 1.3), 0), order_point) - net_stock END AS OQ_order_quantity, CASE WHEN replenishment_method = 'min/max' AND 
                         order_point < Net_stock AND Maximum < Net_stock THEN maximum - Net_stock WHEN replenishment_method = 'OP/OQ' AND 
                         order_point < Net_stock THEN Maximum + order_point - Net_stock WHEN replenishment_method = 'up to' THEN CAST(CASE WHEN WQMetaData.dbo.inlinemax(CAST(forecast_usage AS decimal(19, 2)) 
                         * isnull(periods_to_supply, 1.3), order_point) - net_stock < 0 THEN WQMetaData.dbo.inlinemax(CAST(forecast_usage AS decimal(19, 2)) * isnull(periods_to_supply, 1.3), order_point) - net_stock ELSE 0 END AS int) 
                         ELSE 0 END * - 1 AS excessunits, (CASE WHEN replenishment_method = 'min/max' AND order_point < Net_stock AND Maximum < Net_stock THEN maximum - Net_stock WHEN replenishment_method = 'OP/OQ' AND 
                         order_point < Net_stock THEN Maximum + order_point - Net_stock WHEN replenishment_method = 'up to' THEN CAST(CASE WHEN WQMetaData.dbo.inlinemax(CAST(forecast_usage AS decimal(19, 2)) 
                         * isnull(periods_to_supply, 1.3), order_point) - net_stock < 0 THEN WQMetaData.dbo.inlinemax(CAST(forecast_usage AS decimal(19, 2)) * isnull(periods_to_supply, 1.3), order_point) - net_stock ELSE 0 END AS int) 
                         ELSE 0 END * - 1) * (dbo.vwinventory_lvl1.Value / dbo.vwinventory_lvl1.QtyOnHand) AS excessvalue, dbo.vwinventory_lvl1.manufacturing_class_desc, dbo.vwinventory_lvl1.legacy_id, dbo.vwinventory_lvl1.legacy_company, 
                         dbo.vwinventory_lvl1.qty_backordered_inventory, dbo.vwinventory_lvl1.qty_on_sales_order, dbo.vwinventory_lvl1.qty_for_production, dbo.vwinventory_lvl1.on_sched, dbo.vwinventory_lvl1.qty_in_production, 
                         dbo.vwinventory_lvl1.qty_non_pickable, dbo.vwinventory_lvl1.qty_quarantined, dbo.vwinventory_lvl1.qty_frozen, dbo.vwinventory_lvl1.qty_on_sales_quote, dbo.vwinventory_lvl1.qty_on_special_po, 
                         dbo.vwinventory_lvl1.qty_on_ds_po, dbo.vwinventory_lvl1.qty_on_special_po_cost, dbo.vwinventory_lvl1.Net_qty_available, dbo.vwinventory_lvl1.qty_on_vessel, dbo.vwinventory_lvl1.ItemLocDelete, 
                         dbo.vwinventory_lvl1.Company, dbo.vwinventory_lvl1.Location, dbo.vwinventory_lvl1.InvenMastId, dbo.vwinventory_lvl1.PurchClass, dbo.vwinventory_lvl1.PurchDiscGroup, dbo.vwinventory_lvl1.SalesDiscGroup, 
                         dbo.vwinventory_lvl1.Stock, dbo.vwinventory_lvl1.NoCharge, dbo.vwinventory_lvl1.Requsition, dbo.vwinventory_lvl1.ReplLoc, dbo.vwinventory_lvl1.ReplMethod, dbo.vwinventory_lvl1.FirstPeriod, 
                         dbo.vwinventory_lvl1.FirstYear, dbo.vwinventory_lvl1.Bin, dbo.vwinventory_lvl1.TaxGroup, dbo.vwinventory_lvl1.DeadStock, dbo.vwinventory_lvl1.OnRelease, dbo.vwinventory_lvl1.OnBO, dbo.vwinventory_lvl1.buy, 
                         dbo.vwinventory_lvl1.make, dbo.vwinventory_lvl1.discontinued, dbo.vwinventory_lvl1.track_bins, dbo.vwinventory_lvl1.SupplierId, dbo.vwinventory_lvl1.ProdGroup, dbo.vwinventory_lvl1.DateMod, 
                         dbo.vwinventory_lvl1.DateCreated, dbo.vwinventory_lvl1.LastSale, dbo.vwinventory_lvl1.LastPurchase, dbo.vwinventory_lvl1.STCost, dbo.vwinventory_lvl1.MACost, dbo.vwinventory_lvl1.QtyOnHand, 
                         dbo.vwinventory_lvl1.Non_Special_Qty_on_hand, dbo.vwinventory_lvl1.fifo_cost, dbo.vwinventory_lvl1.QtyOrdered, dbo.vwinventory_lvl1.QtyInTransit, dbo.vwinventory_lvl1.QtyInProcess, dbo.vwinventory_lvl1.QtyAlloc, 
                         dbo.vwinventory_lvl1.QtyBO, dbo.vwinventory_lvl1.QtyReserved, dbo.vwinventory_lvl1.Minimum, dbo.vwinventory_lvl1.Min_OH, dbo.vwinventory_lvl1.Max_OH, dbo.vwinventory_lvl1.Qty_in_transit_mx_oh, 
                         dbo.vwinventory_lvl1.standard_cost, dbo.vwinventory_lvl1.Maximum, dbo.vwinventory_lvl1.weight, dbo.vwinventory_lvl1.LocationPrice1, dbo.vwinventory_lvl1.LocationPrice2, dbo.vwinventory_lvl1.LocationPrice3, 
                         dbo.vwinventory_lvl1.LocationPrice4, dbo.vwinventory_lvl1.LocationPrice5, dbo.vwinventory_lvl1.LocationPrice6, dbo.vwinventory_lvl1.LocationPrice7, dbo.vwinventory_lvl1.LocationPrice8, 
                         dbo.vwinventory_lvl1.LocationPrice9, dbo.vwinventory_lvl1.LocationPrice10, dbo.vwinventory_lvl1.Last_Sale_Date, dbo.vwinventory_lvl1.ItemDesc, dbo.vwinventory_lvl1.ExtendedDesc, dbo.vwinventory_lvl1.ItemId, 
                         dbo.vwinventory_lvl1.Class1, dbo.vwinventory_lvl1.ProdType, dbo.vwinventory_lvl1.Consign, dbo.vwinventory_lvl1.serialized, dbo.vwinventory_lvl1.Catalog, dbo.vwinventory_lvl1.MasterDelete, dbo.vwinventory_lvl1.Class3, 
                         dbo.vwinventory_lvl1.Class2, dbo.vwinventory_lvl1.Class4, dbo.vwinventory_lvl1.Class5, dbo.vwinventory_lvl1.last_maintained_by, dbo.vwinventory_lvl1.inactive, dbo.vwinventory_lvl1.short_code, 
                         dbo.vwinventory_lvl1.track_lots, dbo.vwinventory_lvl1.default_product_group, dbo.vwinventory_lvl1.default_sales_discount_group, dbo.vwinventory_lvl1.default_purchase_disc_group, dbo.vwinventory_lvl1.sales_pricing_unit, 
                         dbo.vwinventory_lvl1.other_charge_item, dbo.vwinventory_lvl1.default_selling_unit, dbo.vwinventory_lvl1.update_via_pricing_service, dbo.vwinventory_lvl1.default_purchasing_unit, dbo.vwinventory_lvl1.convert_quantities, 
                         dbo.vwinventory_lvl1.haz_mat_flag, dbo.vwinventory_lvl1.class_code, dbo.vwinventory_lvl1.item_terms_discount_pct, dbo.vwinventory_lvl1.tpcx_status, dbo.vwinventory_lvl1.default_transfer_unit, 
                         dbo.vwinventory_lvl1.keywords, dbo.vwinventory_lvl1.purchase_pricing_unit, dbo.vwinventory_lvl1.commodity_code, dbo.vwinventory_lvl1.InvMastDateModified, dbo.vwinventory_lvl1.InvMastDateCreated, 
                         dbo.vwinventory_lvl1.net_weight, dbo.vwinventory_lvl1.cube, dbo.vwinventory_lvl1.purchasing_weight, dbo.vwinventory_lvl1.MasterPrice1, dbo.vwinventory_lvl1.MasterPrice2, dbo.vwinventory_lvl1.MasterPrice3, 
                         dbo.vwinventory_lvl1.MasterPrice4, dbo.vwinventory_lvl1.MasterPrice5, dbo.vwinventory_lvl1.MasterPrice6, dbo.vwinventory_lvl1.MasterPrice7, dbo.vwinventory_lvl1.MasterPrice8, dbo.vwinventory_lvl1.MasterPrice9, 
                         dbo.vwinventory_lvl1.MasterPrice10, dbo.vwinventory_lvl1.sales_pricing_unit_size, dbo.vwinventory_lvl1.purchase_pricing_unit_size, dbo.vwinventory_lvl1.R12QtyShip, dbo.vwinventory_lvl1.R12Sales, 
                         dbo.vwinventory_lvl1.R12Cost, dbo.vwinventory_lvl1.R12GM, dbo.vwinventory_lvl1.R12MonthsSold, dbo.vwinventory_lvl1.R12Lines, dbo.vwinventory_lvl1.R12AvgUnits, dbo.vwinventory_lvl1.R12AvgCost, 
                         dbo.vwinventory_lvl1.R12DirectQtyShip, dbo.vwinventory_lvl1.R12DirectSales, dbo.vwinventory_lvl1.R12DirectCost, dbo.vwinventory_lvl1.R12DirectGM, dbo.vwinventory_lvl1.R12DirectLines, 
                         dbo.vwinventory_lvl1.R12WarehouseQtyShip, dbo.vwinventory_lvl1.R12WarehouseSales, dbo.vwinventory_lvl1.R12WarehouseCost, dbo.vwinventory_lvl1.R12WarehouseGM, dbo.vwinventory_lvl1.R12WarehouseLines, 
                         dbo.vwinventory_lvl1.AvgDailyCogs, dbo.vwinventory_lvl1.R12Avg_unit_price, dbo.vwinventory_lvl1.qty_ship_30, dbo.vwinventory_lvl1.qty_ship_60, dbo.vwinventory_lvl1.qty_ship_90, dbo.vwinventory_lvl1.rma_30, 
                         dbo.vwinventory_lvl1.rma_60, dbo.vwinventory_lvl1.rma_90, dbo.vwinventory_lvl1.LocationName, dbo.vwinventory_lvl1.BranchID, dbo.vwinventory_lvl1.LocationDelete, dbo.vwinventory_lvl1.branchname, 
                         dbo.vwinventory_lvl1.division_name, dbo.vwinventory_lvl1.ProdGroupDesc, dbo.vwinventory_lvl1.SupplierName, dbo.vwinventory_lvl1.company_name, dbo.vwinventory_lvl1.Default_Product_Group_Desc, 
                         dbo.vwinventory_lvl1.PurchClassDesc, dbo.vwinventory_lvl1.tax_group_description, dbo.vwinventory_lvl1.commission_class_id, dbo.vwinventory_lvl1.DefaultPurchGroup, dbo.vwinventory_lvl1.PurchGroup, 
                         dbo.vwinventory_lvl1.defaultSalesGroup, dbo.vwinventory_lvl1.SalesGroup, dbo.vwinventory_lvl1.BuyerName, dbo.vwinventory_lvl1.vendor_name, dbo.vwinventory_lvl1.vendor_id, dbo.vwinventory_lvl1.Item_Notes, 
                         dbo.vwinventory_lvl1.Value, dbo.vwinventory_lvl1.Non_special_Value, dbo.vwinventory_lvl1.Value_Mavg, dbo.vwinventory_lvl1.ValueSC, dbo.vwinventory_lvl1.Special_Qty, dbo.vwinventory_lvl1.Special_Value, 
                         dbo.vwinventory_lvl1.SpecialCost, dbo.vwinventory_lvl1.qty_to_transfer, dbo.vwinventory_lvl1.AvailToAllocate, dbo.vwinventory_lvl1.class1desc, dbo.vwinventory_lvl1.class2desc, dbo.vwinventory_lvl1.class3desc, 
                         dbo.vwinventory_lvl1.class4desc, dbo.vwinventory_lvl1.class5desc, dbo.vwinventory_lvl1.upc_code, dbo.vwinventory_lvl1.supplier_part_no, dbo.vwinventory_lvl1.manufacturing_class_id, dbo.vwinventory_lvl1.division_id, 
                         dbo.vwinventory_lvl1.list_price, dbo.vwinventory_lvl1.cost, dbo.vwinventory_lvl1.buyer_id, dbo.vwinventory_lvl1.average_lead_time, dbo.vwinventory_lvl1.FIFOCost, dbo.vwinventory_lvl1.FIFOQty, 
                         dbo.vwinventory_lvl1.FIFOValue, dbo.vwinventory_lvl1.Period1Usage, dbo.vwinventory_lvl1.Period2Usage, dbo.vwinventory_lvl1.Period3Usage, dbo.vwinventory_lvl1.Period4Usage, dbo.vwinventory_lvl1.Period5Usage, 
                         dbo.vwinventory_lvl1.Period6Usage, dbo.vwinventory_lvl1.Period7Usage, dbo.vwinventory_lvl1.Period8Usage, dbo.vwinventory_lvl1.Period9Usage, dbo.vwinventory_lvl1.Period10Usage, dbo.vwinventory_lvl1.Period11Usage, 
                         dbo.vwinventory_lvl1.Period12Usage, dbo.vwinventory_lvl1.PeriodCurrentUsage, dbo.vwinventory_lvl1.Period1Orders, dbo.vwinventory_lvl1.Period2Orders, dbo.vwinventory_lvl1.Period3Orders, 
                         dbo.vwinventory_lvl1.Period4Orders, dbo.vwinventory_lvl1.Period5Orders, dbo.vwinventory_lvl1.Period6Orders, dbo.vwinventory_lvl1.Period7Orders, dbo.vwinventory_lvl1.Period8Orders, dbo.vwinventory_lvl1.Period9Orders, 
                         dbo.vwinventory_lvl1.Period10Orders, dbo.vwinventory_lvl1.Period11Orders, dbo.vwinventory_lvl1.Period12Orders, dbo.vwinventory_lvl1.PeriodCurrentOrders, dbo.vwinventory_lvl1.sched1_usage, 
                         dbo.vwinventory_lvl1.sched2_usage, dbo.vwinventory_lvl1.sched3_usage, dbo.vwinventory_lvl1.sched4_usage, dbo.vwinventory_lvl1.sched5_usage, dbo.vwinventory_lvl1.sched6_usage, 
                         dbo.vwinventory_lvl1.Total_sched_usage_6M, dbo.vwinventory_lvl1.Total12PeriodUsage, dbo.vwinventory_lvl1.forecast_usage, dbo.vwinventory_lvl1.Periods1T6, dbo.vwinventory_lvl1.Periods7T12, 
                         dbo.vwinventory_lvl1.Total12PeriodOrders, dbo.vwinventory_lvl1.order_point, dbo.vwinventory_lvl1.alt_code, dbo.vwinventory_lvl1.orders_1, dbo.vwinventory_lvl1.orders_2, dbo.vwinventory_lvl1.orders_3, 
                         dbo.vwinventory_lvl1.orders_4, dbo.vwinventory_lvl1.orders_5, dbo.vwinventory_lvl1.orders_6, dbo.vwinventory_lvl1.orders_7, dbo.vwinventory_lvl1.orders_8, dbo.vwinventory_lvl1.orders_9, dbo.vwinventory_lvl1.orders_10, 
                         dbo.vwinventory_lvl1.orders_11, dbo.vwinventory_lvl1.orders_12, dbo.vwinventory_lvl1.R12OrderAmt, dbo.vwinventory_lvl1.R12AvgOrderPrice, dbo.vwinventory_lvl1.last_ship_date, dbo.vwinventory_lvl1.last_xfer_date, 
                         dbo.vwinventory_lvl1.last_prod_order_date, dbo.vwinventory_lvl1.last_order_date, dbo.vwinventory_lvl1.last_purch_date, dbo.vwinventory_lvl1.first_purch_date, dbo.vwinventory_lvl1.last_xfer_to_date, 
                         dbo.vwinventory_lvl1.Max_date, dbo.vwinventory_lvl1.Months_old, dbo.vwinventory_lvl1.shipped_1, dbo.vwinventory_lvl1.shipped_2, dbo.vwinventory_lvl1.shipped_3, dbo.vwinventory_lvl1.shipped_4, 
                         dbo.vwinventory_lvl1.shipped_5, dbo.vwinventory_lvl1.shipped_6, dbo.vwinventory_lvl1.shipped_7, dbo.vwinventory_lvl1.shipped_8, dbo.vwinventory_lvl1.shipped_9, dbo.vwinventory_lvl1.shipped_10, 
                         dbo.vwinventory_lvl1.shipped_11, dbo.vwinventory_lvl1.shipped_12, dbo.vwinventory_lvl1.shipped_mtd, dbo.vwinventory_lvl1.total_shipped_last_12_mtd, dbo.vwinventory_lvl1.created_by, 
                         dbo.vwinventory_lvl1.qty_shipped_30d, dbo.vwinventory_lvl1.qty_shipped_60d, dbo.vwinventory_lvl1.qty_shipped_90d, dbo.vwinventory_lvl1.safety_stock_days, dbo.vwinventory_lvl1.lead_time_days, 
                         dbo.vwinventory_lvl1.blanket_PO_qty, dbo.vwinventory_lvl1.Net_stock, dbo.vwinventory_lvl1.demand_pattern, dbo.vwinventory_lvl1.safety_stock_type, dbo.vwinventory_lvl1.demand_pattern_behavior, 
                         dbo.vwinventory_lvl1.periods_to_supply_max, dbo.vwinventory_lvl1.periods_to_supply_min, dbo.vwinventory_lvl1.replenishment_method, dbo.vwinventory_lvl1.last_rec_po, dbo.vwinventory_lvl1.last_rec_po_with_disc, 
                         periods_to_supply.inv_mast_uid, periods_to_supply.location_id, periods_to_supply.periods_to_supply, dbo.vwinventory_lvl1.supplier_sort_code, dbo.vwinventory_lvl1.legacy_item_id, 
                         dbo.vwinventory_lvl1.legacy_item_description
FROM            dbo.vwinventory_lvl1 LEFT OUTER JOIN
                             (SELECT        inv_loc.inv_mast_uid, inv_loc.location_id, CASE WHEN COALESCE (inv_period_usage.forecast_usage, 0.000000000) 
                                                         * company.number_of_demand_periods / item_uom.unit_size > COALESCE (NULLIF (location.high_velocity_level, 0), CAST(ss_high.value AS decimal(9))) THEN COALESCE (high_level_months, 0.000000000) 
                                                         WHEN COALESCE (inv_period_usage.forecast_usage, 0.000000000) * company.number_of_demand_periods / item_uom.unit_size > COALESCE (NULLIF (location.mid_velocity_level, 0), 
                                                         CAST(ss_mid.value AS decimal(9))) THEN COALESCE (mid_level_months, 0.000000000) ELSE COALESCE (low_level_months, 0.000000000) END AS periods_to_supply
                               FROM            P21.dbo.inv_loc AS inv_loc INNER JOIN
                                                         P21.dbo.company AS company ON company.company_id = inv_loc.company_id INNER JOIN
                                                         P21.dbo.inv_mast AS inv_mast ON inv_loc.inv_mast_uid = inv_mast.inv_mast_uid AND inv_mast.delete_flag = 'N' INNER JOIN
                                                         P21.dbo.location AS location ON location.location_id = inv_loc.location_id INNER JOIN
                                                         P21.dbo.item_uom AS item_uom ON item_uom.inv_mast_uid = inv_mast.inv_mast_uid AND item_uom.unit_of_measure = inv_mast.default_selling_unit LEFT OUTER JOIN
                                                         P21.dbo.purchase_class AS purchase_class ON purchase_class.purchase_class_id = inv_loc.purchase_class LEFT OUTER JOIN
                                                         P21.dbo.demand_period AS demand_period ON demand_period.company_id = inv_loc.company_id AND GETDATE() BETWEEN demand_period.beginning_date AND demand_period.ending_date LEFT OUTER JOIN
                                                         P21.dbo.inv_period_usage AS inv_period_usage WITH (NOLOCK) ON inv_period_usage.demand_period_uid = demand_period.demand_period_uid AND 
                                                         inv_period_usage.inv_mast_uid = inv_loc.inv_mast_uid AND inv_period_usage.location_id = inv_loc.location_id CROSS JOIN
                                                         P21.dbo.system_setting AS ss_cost_basis CROSS JOIN
                                                         P21.dbo.system_setting AS ss_high CROSS JOIN
                                                         P21.dbo.system_setting AS ss_mid CROSS JOIN
                                                         P21.dbo.system_setting AS eoqlimit
                               WHERE        (eoqlimit.name = 'useeoqlimitsontransfers') AND (ss_high.configuration_id = 0) AND (ss_high.name = 'high_velocity_level') AND (ss_mid.configuration_id = 0) AND (ss_mid.name = 'mid_velocity_level') AND 
                                                         (ss_cost_basis.configuration_id = 0) AND (ss_cost_basis.name = 'inventory_costing_basis') AND (inv_loc.replenishment_method IN ('UP TO', 'EOQ'))) AS periods_to_supply ON 
                         periods_to_supply.inv_mast_uid = dbo.vwinventory_lvl1.InvenMastId AND periods_to_supply.location_id = dbo.vwinventory_lvl1.Location