--DW d_dw_aptb_rpt_vendor
SELECT apinv_hdr.company_no company_id, apinv_hdr.vendor_id, apinv_hdr.invoice_no, apinv_hdr.invoice_amount, apinv_hdr.invoice_date, apinv_hdr.net_due_date, apinv_hdr.terms_due_date, (SELECT IsNULL(SUM(payment_detail.amount_paid + payment_detail.currency_variance_amount), 0) + COALESCE(SUM(drv_iva_totals.total_iva_amount_withheld), 0) + COALESCE(SUM(drv_iva_totals.total_iva_amount_reduced), 0)  FROM payments INNER JOIN payment_detail ON payment_detail.company_no = payments.company_no       AND payment_detail.bank_no = payments.bank_no  AND payment_detail.check_no = payments.check_no  LEFT JOIN (SELECT payment_detail_iva.payment_detail_uid      ,SUM(CASE WHEN payment_detail_iva.iva_withheld_flag = 'Y' THEN payment_detail_iva.iva_amount_paid ELSE 0 END) 'total_iva_amount_withheld'    ,SUM(CASE WHEN payment_detail_iva.iva_received_flag = 'Y' THEN payment_detail_iva.iva_paid_reduced_amt ELSE 0 END) 'total_iva_amount_reduced' FROM  payment_detail_iva INNER JOIN payment_detail ON payment_detail.payment_detail_uid = payment_detail_iva.payment_detail_uid   GROUP BY payment_detail_iva.payment_detail_uid) AS drv_iva_totals ON drv_iva_totals.payment_detail_uid = payment_detail.payment_detail_uid     WHERE (payments.year_for_period < 2024 OR    (payments.year_for_period = 2024 AND     payments.period <= 1 )) AND  ((payments.void_year is NULL and   payments.void_period is NULL) or   ((payments.void_year > 2024) or   (payments.void_year = 2024 and   payments.void_period > 1))) and   payment_detail.voucher_no = apinv_hdr.voucher_no) amount_paid,      (SELECT IsNULL( SUM(payment_detail.terms_amount_taken), 0 )      
FROM payments, payment_detail      
WHERE payment_detail.company_no = payments.company_no and payment_detail.bank_no = payments.bank_no and    payment_detail.check_no = payments.check_no and    (payments.year_for_period < 2024 or    (payments.year_for_period = 2024 and    payments.period <= 1 )) and  ((payments.void_year is NULL and   payments.void_period is NULL) or   ((payments.void_year > 2024) or   (payments.void_year = 2024 and   payments.void_period > 1))) and   payment_detail.voucher_no = apinv_hdr.voucher_no) terms_amount,      (SELECT IsNULL( SUM(apinv_hdr_memo.memo_amount), 0 )     FROM apinv_hdr 
apinv_hdr_memo    WHERE apinv_hdr.voucher_no = apinv_hdr_memo.voucher_reference_number and     apinv_hdr_memo.voucher_type <> 'V' and     apinv_hdr_memo.voucher_no <> apinv_hdr_memo.voucher_reference_number and     apinv_hdr_memo.approved = 'Y' and     ( 
apinv_hdr_memo.year_for_period < 2024 or     ( apinv_hdr_memo.period <= 1 and       apinv_hdr_memo.year_for_period = 2024))) memo_amount, apinv_hdr.voucher_no,       company.company_name,       CASE COALESCE(vendor.vendor_on_hold_flag, 'N')    WHEN 'Y' THEN      
address.name + ' ***Vendor On Hold***'    ELSE      address.name    END address_name,       apinv_hdr.date_created,       apinv_hdr.date_last_modified,       apinv_hdr.last_maintained_by,       apinv_hdr.period,       apinv_hdr.year_for_period year,       
apinv_hdr.branch_id,       branch.branch_description,    CASE WHEN p21_view_apinv_hdr_disputed.compute_disputed_flag = 'N'       THEN 'N'       ELSE 'Y'      END 'disputed_flag',    p21_view_apinv_hdr_disputed.total_disputed_amount 'disputed_amt',    
location.location_id   ,currency_hdr.currency_desc     ,company.home_currency_id   ,apinv_hdr.currency_id voucher_currency_id   ,home_curr_hdr.currency_desc curr_desc_home   ,coalesce(currency_hdr.currency_desc, home_curr_hdr.currency_desc) cc_curr_desc   
,coalesce(apinv_hdr.currency_id, company.home_currency_id) cc_curr_id  ,apinv_hdr.invoice_amount_display,    (SELECT IsNULL(SUM(payment_detail.amount_paid_display), 0) + COALESCE(SUM(drv_iva_totals.total_iva_amount_withheld_display), 0) + 
COALESCE(SUM(drv_iva_totals.total_iva_amount_reduced_display), 0)  FROM payments INNER JOIN payment_detail ON payment_detail.company_no = payments.company_no       AND payment_detail.bank_no = payments.bank_no  AND 
payment_detail.check_no = payments.check_no  LEFT JOIN (SELECT payment_detail_iva.payment_detail_uid      ,SUM(CASE WHEN payment_detail_iva.iva_withheld_flag = 'Y' THEN payment_detail_iva.iva_amount_paid_display ELSE 0 END) 'total_iva_amount_withheld_display'    ,SUM(CASE WHEN payment_detail_iva.iva_received_flag = 'Y' THEN payment_detail_iva.iva_paid_reduced_amt_display ELSE 0 END) 'total_iva_amount_reduced_display' FROM  payment_detail_iva INNER JOIN payment_detail ON payment_detail.payment_detail_uid = payment_detail_iva.payment_detail_uid   GROUP BY payment_detail_iva.payment_detail_uid) AS drv_iva_totals ON drv_iva_totals.payment_detail_uid = payment_detail.payment_detail_uid     WHERE (payments.year_for_period < 2024 OR    (payments.year_for_period = 2024 AND     payments.period <= 1 )) AND       ((payments.void_year is NULL and   payments.void_period is NULL) or   ((payments.void_year > 2024) or   (payments.void_year = 2024 and   payments.void_period > 1))) and   payment_detail.voucher_no = apinv_hdr.voucher_no) amount_paid_display,     (SELECT Isnull(SUM(payment_detail.terms_amount_taken_display), 0)    FROM   payments,     payment_detail    WHERE  payment_detail.company_no = payments.company_no     AND payment_detail.bank_no = payments.bank_no     AND payment_detail.check_no = payments.check_no     AND ( payments.year_for_period < 2024     OR ( payments.year_for_period = 2024    AND payments.period <= 1 ) )     AND ( ( payments.void_year IS NULL      AND payments.void_period IS NULL )     OR ( ( payments.void_year > 2024 )     OR ( payments.void_year = 2024   AND payments.void_period > 1 ) ) )     AND payment_detail.voucher_no = apinv_hdr.voucher_no)   terms_amount_display,   (SELECT Isnull(SUM(apinv_hdr_memo.memo_amount_display), 0)    FROM   apinv_hdr apinv_hdr_memo    WHERE  apinv_hdr.voucher_no = apinv_hdr_memo.voucher_reference_number     AND apinv_hdr_memo.voucher_type <> 'V'     AND 
apinv_hdr_memo.voucher_no <>  apinv_hdr_memo.voucher_reference_number     AND apinv_hdr_memo.approved = 'Y'     AND ( apinv_hdr_memo.year_for_period < 2024     OR ( apinv_hdr_memo.period <= 
1    AND apinv_hdr_memo.year_for_period = 2024 ) ))   memo_amount_display,     p21_view_apinv_hdr_disputed.total_disputed_amount_display 'disputed_amt_display'    ,(CASE    WHEN (company.home_currency_id = Coalesce(apinv_hdr.currency_id, 
company.home_currency_id)) THEN    'N'   ELSE    'Y'   END) cc_FCVoucher    ,coalesce(company.use_branch_accounting,'N') use_branch   ,system_setting.value foreign_curr_ss      FROM apinv_hdr    INNER JOIN company ON company.company_id = apinv_hdr.company_no     
INNER JOIN address ON address.id = apinv_hdr.vendor_id       INNER JOIN p21_view_apinv_hdr_disputed ON p21_view_apinv_hdr_disputed.voucher_no = apinv_hdr.voucher_no    LEFT JOIN branch ON branch.company_id = apinv_hdr.company_no AND branch.branch_id = 
apinv_hdr.branch_id    LEFT JOIN location ON location.location_id = apinv_hdr.vendor_id       AND location.company_id <> apinv_hdr.company_no     LEFT JOIN currency_hdr ON currency_hdr.currency_id = apinv_hdr.currency_id     LEFT JOIN currency_hdr 
home_curr_hdr ON home_curr_hdr.currency_id = company.home_currency_id    inner join system_setting on system_setting.name = 'foreign_currency'   INNER JOIN vendor ON vendor.company_id = apinv_hdr.company_no   AND vendor.vendor_id = apinv_hdr.vendor_id     
WHERE     ( apinv_hdr.company_no = '1' ) and    ( ( apinv_hdr.branch_id >= ' ' and apinv_hdr.branch_id <= 'ZZZZZZZZ'  ) or      ( apinv_hdr.branch_id IS NULL  )  ) and    ( apinv_hdr.approved = 'Y' ) and    ( apinv_hdr.vendor_id >= 0 )and       ( 
apinv_hdr.vendor_id <= 99999999 ) and    ( apinv_hdr.year_for_period < 2024 or    ( apinv_hdr.period <= 1 and      apinv_hdr.year_for_period = 2024)) and ( apinv_hdr.date_created >= '1990-01-01 00:00:00.000' )and ( apinv_hdr.date_created <= '2049-12-31 00:00:00.000' )and ( apinv_hdr.date_last_modified >= '1990-01-01 00:00:00.000' )and ( apinv_hdr.date_last_modified <= '2049-12-31 00:00:00.000' ) and ( apinv_hdr.last_maintained_by >= ' ' ) and ( apinv_hdr.last_maintained_by <= 'ZZZZZZZ' ) and     ( apinv_hdr.year_fully_paid > 2024 or    ( apinv_hdr.year_fully_paid = 2024 and      apinv_hdr.period_fully_paid > 1) or    ( apinv_hdr.year_fully_paid is NULL and      apinv_hdr.period_fully_paid is NULL) OR      ('N' = 'Y' AND      apinv_hdr.year_fully_paid = 2024 AND      apinv_hdr.period_fully_paid = 1)) and    ( ('Y' = 'Y') OR      (p21_view_apinv_hdr_disputed.compute_disputed_flag = 'N' AND 'Y' ='N') OR      (p21_view_apinv_hdr_disputed.compute_disputed_flag <> 'N' AND 'Y' ='O') ) AND     (apinv_hdr.voucher_no = apinv_hdr.voucher_reference_number OR (apinv_hdr.voucher_no <> apinv_hdr.voucher_reference_number AND COALESCE(apinv_hdr.reverse_flag, 'N') = 'Y'))     AND     apinv_hdr.voucher_type IN ('V','C','D') AND  ( ('Y' = 'Y') OR     ('Y' = 'N' AND location.location_id IS NULL) OR     ('Y' = 'O' AND location.location_id IS NOT NULL) )   AND (0 = 0 OR coalesce(apinv_hdr.currency_id, company.home_currency_id) = 0)   AND (COALESCE(2982, 2982) = 2982 OR vendor.vendor_type_cd = 2982)  ORDER BY coalesce(currency_hdr.currency_desc, home_curr_hdr.currency_desc) ASC,     coalesce(apinv_hdr.currency_id, company.home_currency_id) ASC,    apinv_hdr.vendor_id ASC, address.name ASC, apinv_hdr.branch_id ASC, apinv_hdr.voucher_no ASC       