--DW d_artb_temp_bal_bycust
  SELECT artb_temp.company_id, artb_temp.invoice_no, artb_temp.total_amount, artb_temp.memo_amount, artb_temp.bad_debt_amount, CAST(CONVERT(VarChar(11), artb_temp.invoice_date, 113) AS DateTime) 'invoice_date',  artb_temp.terms_desc, artb_temp.allowed_amount, artb_temp.salesrep_id, artb_temp.order_date, artb_temp.customer_id, address.name, company.company_name, artb_temp.date_created, artb_temp.date_last_modified, artb_temp.last_maintained_by, 
artb_temp.period, artb_temp.total_receipts, artb_temp.year_for_period, artb_temp.order_no, artb_temp.terms_amount, artb_temp.net_due_date, artb_temp.terms_due_date, branch.branch_description, artb_temp.branch_id, 
contacts.first_name, contacts.mi, contacts.last_name,  COALESCE(artb_temp.currency_id, company.home_currency_id),  COALESCE( artb_temp.total_amount_home, artb_temp.total_amount ) total_amount_home,  COALESCE( artb_temp.memo_amount_home, artb_temp.memo_amount ) 
memo_amount_home,  COALESCE( artb_temp.bad_debt_amount_home, artb_temp.bad_debt_amount ) bad_debt_amount_home,  COALESCE( artb_temp.allowed_home, artb_temp.allowed_amount ) allowed_home,  COALESCE( artb_temp.terms_amount_home, artb_temp.terms_amount ) 
terms_amount_home,  COALESCE( artb_temp.total_receipts_home, artb_temp.total_receipts ) total_receipts_home,  (CASE   WHEN (company.home_currency_id = coalesce(artb_temp.to_currency_id, company.home_currency_id)) THEN   'N'  ELSE   'Y'  END) cc_CustomerUsingFC,  
artb_temp.invoice_reference_no,  artb_temp.invoice_adjustment_type,  artb_temp.corp_address_id,  corporate_address.name corporate_name,  address.central_phone_number   ,artb_temp.tax_terms_taken_amt   ,coalesce( artb_temp.tax_terms_taken_amt_home, 
artb_temp.tax_terms_taken_amt ) tax_terms_taken_amt_home  ,artb_temp.inter_company  
FROM p21_fnt_artb(2024001, '1', 'N', '0', '99999999', 0, '2023-12-18 00:00:00', 'N', 0, 99999999) artb_temp INNER JOIN address ON ( address.id = artb_temp.customer_id )    
INNER JOIN company ON ( company.company_id = artb_temp.company_id )    INNER JOIN customer ON ( customer.customer_id = artb_temp.customer_id ) AND   ( customer.company_id = artb_temp.company_id )   LEFT JOIN branch ON ( branch.company_id = artb_temp.company_id ) AND     ( branch.branch_id = artb_temp.branch_id ) LEFT OUTER JOIN contacts ON ( contacts.id = artb_temp.salesrep_id ) LEFT JOIN address corporate_address ON corporate_address.id = artb_temp.corp_address_id  WHERE ( artb_temp.total_receipts <> ((artb_temp.total_amount + memo_amount + bad_debt_amount) - allowed_amount - terms_amount - tax_terms_taken_amt) )    AND (('Y' = 'Y' AND artb_temp.salesrep_id IS NULL)   OR artb_temp.salesrep_id BETWEEN '0' AND '99999999')   AND ('N' = 'N'   OR artb_temp.customer_id IN    (   SELECT artb_temp2.customer_id  FROM p21_fnt_artb_customer(2024001, '1', '0', '99999999', 'N', 0, '2023-12-18 00:00:00', 0, 99999999) artb_temp2    WHERE artb_temp2.net_due_date <= '2023-12-18 00:00:00.000'   AND ( 'A' = 'A'   OR ('D' = 'A' AND artb_temp2.summary_amount > 0)   OR ('C' = 'A' AND artb_temp2.summary_amount < 0) )   GROUP BY artb_temp2.customer_id    ))   AND COALESCE(artb_temp.currency_id, company.home_currency_id) BETWEEN 0 AND 99999999    AND ( ( artb_temp.branch_id BETWEEN '0' AND 'ZZZZZZZZ' )    OR ( artb_temp.branch_id IS NULL ))    AND (('1990-01-01 00:00:00.000' = '1990-01-01 00:00:00.000' AND '2049-12-31 00:00:00.000' = '2049-12-31 00:00:00.000')  OR artb_temp.date_created BETWEEN '1990-01-01 00:00:00.000' AND '2049-12-31 00:00:00.000')  AND (('1990-01-01 00:00:00.000' = '1990-01-01 00:00:00.000' AND '2049-12-31 00:00:00.000' = '2049-12-31 00:00:00.000')  OR artb_temp.date_last_modified BETWEEN '1990-01-01 00:00:00.000' AND '2049-12-31 00:00:00.000')   AND artb_temp.last_maintained_by BETWEEN ' ' AND 'ZZZZZZZ'   AND artb_temp.approved = 'Y'   AND artb_temp.corp_address_id BETWEEN 0 AND 99999999